import "dotenv/config";
import { createClient } from "@supabase/supabase-js";

const supabaseUrl = process.env.NEXT_PUBLIC_SUPABASE_URL || process.env.SUPABASE_URL!;
const supabaseKey = process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY || process.env.SUPABASE_ANON_KEY!;

if (!supabaseUrl || !supabaseKey) {
  throw new Error("Missing Supabase credentials");
}

const supabase = createClient(supabaseUrl, supabaseKey);

const phones2025_2026 = [
  // ==================== SAMSUNG 2025 ====================
  
  // Samsung Galaxy S25 Ultra
  {
    slug: "samsung-galaxy-s25-ultra",
    name: "Samsung Galaxy S25 Ultra",
    name_ar: "سامسونج جالاكسي S25 ألترا",
    brand: "Samsung",
    year: 2025,
    release_date: "يناير 2025",
    image: "https://fdn2.gsmarena.com/vv/bigpic/samsung-galaxy-s25-ultra.jpg",
    status: "published",
    quick_screen: "6.9 بوصة Dynamic AMOLED 2X، 120Hz",
    quick_processor: "Snapdragon 8 Elite",
    quick_camera: "200 ميجابكسل رئيسية",
    quick_front_camera: "12 ميجابكسل",
    quick_memory: "256/512GB/1TB مع 12GB رام",
    quick_battery: "5000 مللي أمبير، شحن 45 واط",
    design_height: "162.8 ملم",
    design_width: "77.6 ملم",
    design_thickness: "8.2 ملم",
    design_weight: "218 جرام",
    design_materials: "زجاج Gorilla Armor 2، إطار من التيتانيوم",
    design_colors: "أسود تيتانيوم، رمادي تيتانيوم، فضي تيتانيوم، أزرق تيتانيوم",
    design_frame: "إطار من التيتانيوم",
    screen_type: "Dynamic AMOLED 2X",
    screen_size: "6.9 بوصة",
    screen_resolution: "1440 × 3120 بكسل",
    screen_ppi: "505 بكسل لكل بوصة",
    screen_refresh_rate: "120Hz",
    screen_touch_rate: "240Hz",
    screen_brightness: "2600 نيت",
    screen_protection: "Corning Gorilla Armor 2",
    screen_back_protection: "Gorilla Glass Victus 2",
    processor_name: "Qualcomm Snapdragon 8 Elite (3nm)",
    processor_cores: "ثماني النواة",
    processor_frequency: "1×4.32 GHz + 3×3.53 GHz + 4×2.75 GHz",
    processor_gpu: "Adreno 830",
    processor_fabrication: "3 نانومتر",
    antutu_score: "2,850,000",
    memory_storage: "256/512GB/1TB",
    memory_ram: "12GB",
    memory_type: "UFS 4.0",
    memory_sd_card: "لا",
    camera_main: "200 ميجابكسل، f/1.7، OIS، PDAF متعدد الاتجاهات",
    camera_ultrawide: "50 ميجابكسل، f/1.9، زاوية فائقة الاتساع 120°",
    camera_telephoto: "50 ميجابكسل، f/3.4، تقريب بصري 5× + 10 ميجابكسل، f/2.4، تقريب بصري 3×",
    camera_macro: "دمج في الكاميرا الرئيسية",
    camera_front: "12 ميجابكسل، f/2.2",
    camera_video: "8K@30fps، 4K@60fps مع HDR10+، Super Steady",
    audio_speakers: "ستيريو من AKG",
    audio_jack: "لا",
    connectivity_sim: "Nano-SIM + eSIM",
    connectivity_network: "5G SA/NSA، 4G LTE",
    connectivity_wifi: "Wi-Fi 7 (802.11be)",
    connectivity_bluetooth: "5.4",
    connectivity_nfc: "نعم",
    connectivity_gps: "GPS، Galileo، GLONASS، BeiDou، QZSS",
    protection_water: "IP68",
    protection_standard: "IP68 (مقاومة الماء حتى 1.5 متر لمدة 30 دقيقة)",
    battery_capacity: "5000 مللي أمبير",
    battery_charging: "45 واط سلكي، PD 3.0",
    battery_wireless: "15 واط لاسلكي",
    battery_reverse: "4.5 واط عكسي لاسلكي",
    software_os: "Android 15",
    software_ui: "One UI 7",
    sensor_fingerprint: "بالموجات فوق الصوتية تحت الشاشة",
    sensor_face_unlock: "نعم",
    sensor_gyroscope: "نعم",
    sensor_compass: "نعم",
    sensor_proximity: "نعم",
    sensor_light: "نعم",
    sensor_other: "مقياس التسارع، البارومتر، Hall، S Pen"
  },

  // Samsung Galaxy S25+
  {
    slug: "samsung-galaxy-s25-plus",
    name: "Samsung Galaxy S25+",
    name_ar: "سامسونج جالاكسي S25 بلس",
    brand: "Samsung",
    year: 2025,
    release_date: "يناير 2025",
    image: "https://fdn2.gsmarena.com/vv/bigpic/samsung-galaxy-s25-plus.jpg",
    status: "published",
    quick_screen: "6.7 بوصة Dynamic AMOLED 2X، 120Hz",
    quick_processor: "Snapdragon 8 Elite",
    quick_camera: "50 ميجابكسل رئيسية",
    quick_front_camera: "12 ميجابكسل",
    quick_memory: "256/512GB مع 12GB رام",
    quick_battery: "4900 مللي أمبير، شحن 45 واط",
    design_height: "158.4 ملم",
    design_width: "75.8 ملم",
    design_thickness: "7.3 ملم",
    design_weight: "190 جرام",
    design_materials: "زجاج Gorilla Glass Victus 2، إطار ألمنيوم",
    design_colors: "أزرق جليدي، أسود، فضي، أخضر نعناعي",
    design_frame: "إطار ألمنيوم",
    screen_type: "Dynamic AMOLED 2X",
    screen_size: "6.7 بوصة",
    screen_resolution: "1440 × 3120 بكسل",
    screen_ppi: "513 بكسل لكل بوصة",
    screen_refresh_rate: "120Hz",
    screen_brightness: "2600 نيت",
    screen_protection: "Corning Gorilla Glass Victus 2",
    processor_name: "Qualcomm Snapdragon 8 Elite (3nm)",
    processor_cores: "ثماني النواة",
    processor_frequency: "1×4.32 GHz + 3×3.53 GHz + 4×2.75 GHz",
    processor_gpu: "Adreno 830",
    processor_fabrication: "3 نانومتر",
    antutu_score: "2,850,000",
    memory_storage: "256/512GB",
    memory_ram: "12GB",
    memory_type: "UFS 4.0",
    memory_sd_card: "لا",
    camera_main: "50 ميجابكسل، f/1.8، OIS، Dual Pixel PDAF",
    camera_ultrawide: "12 ميجابكسل، f/2.2، زاوية واسعة 120°",
    camera_telephoto: "10 ميجابكسل، f/2.4، تقريب بصري 3×، OIS",
    camera_front: "12 ميجابكسل، f/2.2",
    camera_video: "8K@30fps، 4K@60fps",
    audio_speakers: "ستيريو من AKG",
    audio_jack: "لا",
    connectivity_sim: "Nano-SIM + eSIM",
    connectivity_network: "5G SA/NSA",
    connectivity_wifi: "Wi-Fi 7",
    connectivity_bluetooth: "5.4",
    connectivity_nfc: "نعم",
    connectivity_gps: "GPS، GLONASS، Galileo، BeiDou، QZSS",
    protection_water: "IP68",
    protection_standard: "IP68",
    battery_capacity: "4900 مللي أمبير",
    battery_charging: "45 واط",
    battery_wireless: "15 واط",
    battery_reverse: "4.5 واط",
    software_os: "Android 15",
    software_ui: "One UI 7",
    sensor_fingerprint: "بالموجات فوق الصوتية تحت الشاشة",
    sensor_face_unlock: "نعم",
    sensor_gyroscope: "نعم",
    sensor_compass: "نعم",
    sensor_proximity: "نعم",
    sensor_light: "نعم",
    sensor_other: "مقياس التسارع، البارومتر"
  },

  // Samsung Galaxy S25
  {
    slug: "samsung-galaxy-s25",
    name: "Samsung Galaxy S25",
    name_ar: "سامسونج جالاكسي S25",
    brand: "Samsung",
    year: 2025,
    release_date: "يناير 2025",
    image: "https://fdn2.gsmarena.com/vv/bigpic/samsung-galaxy-s25.jpg",
    status: "published",
    quick_screen: "6.2 بوصة Dynamic AMOLED 2X، 120Hz",
    quick_processor: "Snapdragon 8 Elite",
    quick_camera: "50 ميجابكسل رئيسية",
    quick_front_camera: "12 ميجابكسل",
    quick_memory: "128/256/512GB مع 12GB رام",
    quick_battery: "4000 مللي أمبير، شحن 25 واط",
    design_height: "146.9 ملم",
    design_width: "70.5 ملم",
    design_thickness: "7.2 ملم",
    design_weight: "162 جرام",
    design_materials: "زجاج Gorilla Glass Victus 2، إطار ألمنيوم",
    design_colors: "أزرق بحري، أخضر نعناعي، فضي، أسود",
    design_frame: "إطار ألمنيوم",
    screen_type: "Dynamic AMOLED 2X",
    screen_size: "6.2 بوصة",
    screen_resolution: "1080 × 2340 بكسل",
    screen_ppi: "416 بكسل لكل بوصة",
    screen_refresh_rate: "120Hz",
    screen_brightness: "2600 نيت",
    screen_protection: "Corning Gorilla Glass Victus 2",
    processor_name: "Qualcomm Snapdragon 8 Elite (3nm)",
    processor_cores: "ثماني النواة",
    processor_frequency: "1×4.32 GHz + 3×3.53 GHz + 4×2.75 GHz",
    processor_gpu: "Adreno 830",
    processor_fabrication: "3 نانومتر",
    antutu_score: "2,850,000",
    memory_storage: "128/256/512GB",
    memory_ram: "12GB",
    memory_type: "UFS 4.0",
    memory_sd_card: "لا",
    camera_main: "50 ميجابكسل، f/1.8، OIS، Dual Pixel PDAF",
    camera_ultrawide: "12 ميجابكسل، f/2.2، زاوية واسعة 120°",
    camera_telephoto: "10 ميجابكسل، f/2.4، تقريب بصري 3×، OIS",
    camera_front: "12 ميجابكسل، f/2.2",
    camera_video: "8K@30fps، 4K@60fps",
    audio_speakers: "ستيريو من AKG",
    audio_jack: "لا",
    connectivity_sim: "Nano-SIM + eSIM",
    connectivity_network: "5G SA/NSA",
    connectivity_wifi: "Wi-Fi 7",
    connectivity_bluetooth: "5.4",
    connectivity_nfc: "نعم",
    connectivity_gps: "GPS، GLONASS، Galileo، BeiDou، QZSS",
    protection_water: "IP68",
    protection_standard: "IP68",
    battery_capacity: "4000 مللي أمبير",
    battery_charging: "25 واط",
    battery_wireless: "15 واط",
    battery_reverse: "4.5 واط",
    software_os: "Android 15",
    software_ui: "One UI 7",
    sensor_fingerprint: "بالموجات فوق الصوتية تحت الشاشة",
    sensor_face_unlock: "نعم",
    sensor_gyroscope: "نعم",
    sensor_compass: "نعم",
    sensor_proximity: "نعم",
    sensor_light: "نعم",
    sensor_other: "مقياس التسارع، البارومتر"
  },

  // Samsung Galaxy S25 FE
  {
    slug: "samsung-galaxy-s25-fe",
    name: "Samsung Galaxy S25 FE",
    name_ar: "سامسونج جالاكسي S25 FE",
    brand: "Samsung",
    year: 2025,
    release_date: "أكتوبر 2025",
    image: "https://fdn2.gsmarena.com/vv/bigpic/samsung-galaxy-s25-fe.jpg",
    status: "published",
    quick_screen: "6.7 بوصة Dynamic AMOLED 2X، 120Hz",
    quick_processor: "Exynos 2500",
    quick_camera: "50 ميجابكسل رئيسية",
    quick_front_camera: "10 ميجابكسل",
    quick_memory: "128/256GB مع 8GB رام",
    quick_battery: "4700 مللي أمبير، شحن 25 واط",
    design_height: "162.0 ملم",
    design_width: "77.3 ملم",
    design_thickness: "8.0 ملم",
    design_weight: "195 جرام",
    design_materials: "زجاج Gorilla Glass Victus 2، إطار ألمنيوم",
    design_colors: "أخضر زيتوني، أزرق، رمادي، أبيض",
    design_frame: "إطار ألمنيوم",
    screen_type: "Dynamic AMOLED 2X",
    screen_size: "6.7 بوصة",
    screen_resolution: "1080 × 2400 بكسل",
    screen_ppi: "393 بكسل لكل بوصة",
    screen_refresh_rate: "120Hz",
    screen_brightness: "1900 نيت",
    screen_protection: "Corning Gorilla Glass Victus 2",
    processor_name: "Samsung Exynos 2500 (3nm)",
    processor_cores: "ثماني النواة",
    processor_frequency: "1×3.2 GHz + 3×2.9 GHz + 4×2.2 GHz",
    processor_gpu: "Xclipse 950",
    processor_fabrication: "3 نانومتر",
    antutu_score: "2,100,000",
    memory_storage: "128/256GB",
    memory_ram: "8GB",
    memory_type: "UFS 3.1",
    memory_sd_card: "لا",
    camera_main: "50 ميجابكسل، f/1.8، OIS، PDAF",
    camera_ultrawide: "12 ميجابكسل، f/2.2، زاوية واسعة 120°",
    camera_telephoto: "8 ميجابكسل، f/2.4، تقريب بصري 3×",
    camera_front: "10 ميجابكسل، f/2.4",
    camera_video: "4K@60fps، 1080p@240fps",
    audio_speakers: "ستيريو",
    audio_jack: "لا",
    connectivity_sim: "Nano-SIM + eSIM",
    connectivity_network: "5G SA/NSA",
    connectivity_wifi: "Wi-Fi 6E",
    connectivity_bluetooth: "5.3",
    connectivity_nfc: "نعم",
    connectivity_gps: "GPS، GLONASS، Galileo، BeiDou",
    protection_water: "IP68",
    protection_standard: "IP68",
    battery_capacity: "4700 مللي أمبير",
    battery_charging: "25 واط",
    battery_wireless: "15 واط",
    battery_reverse: "4.5 واط",
    software_os: "Android 15",
    software_ui: "One UI 7",
    sensor_fingerprint: "بصري تحت الشاشة",
    sensor_face_unlock: "نعم",
    sensor_gyroscope: "نعم",
    sensor_compass: "نعم",
    sensor_proximity: "نعم",
    sensor_light: "نعم",
    sensor_other: "مقياس التسارع"
  },

  // Samsung Galaxy Z Fold 6
  {
    slug: "samsung-galaxy-z-fold6",
    name: "Samsung Galaxy Z Fold 6",
    name_ar: "سامسونج جالاكسي Z فولد 6",
    brand: "Samsung",
    year: 2025,
    release_date: "يوليو 2025",
    image: "https://fdn2.gsmarena.com/vv/bigpic/samsung-galaxy-z-fold6.jpg",
    status: "published",
    quick_screen: "7.6 بوصة داخلية + 6.3 بوصة خارجية",
    quick_processor: "Snapdragon 8 Gen 3",
    quick_camera: "50 ميجابكسل رئيسية",
    quick_front_camera: "10 ميجابكسل + 4 ميجابكسل تحت الشاشة",
    quick_memory: "256/512GB/1TB مع 12GB رام",
    quick_battery: "4400 مللي أمبير، شحن 25 واط",
    design_height: "153.5 × 132.6 ملم (مفتوح)",
    design_width: "68.1 ملم (مغلق)",
    design_thickness: "5.6 ملم (مفتوح)، 12.1 ملم (مغلق)",
    design_weight: "239 جرام",
    design_materials: "زجاج Gorilla Glass Victus 2، إطار ألمنيوم Armor",
    design_colors: "أزرق بحري، فضي، وردي، أسود",
    design_frame: "إطار ألمنيوم Armor",
    screen_type: "Dynamic AMOLED 2X (داخلية وخارجية)",
    screen_size: "7.6 بوصة داخلية، 6.3 بوصة خارجية",
    screen_resolution: "2160 × 1856 بكسل (داخلية)، 968 × 2376 بكسل (خارجية)",
    screen_ppi: "374 بكسل لكل بوصة (داخلية)",
    screen_refresh_rate: "120Hz",
    screen_brightness: "2600 نيت",
    screen_protection: "Gorilla Glass Victus 2",
    processor_name: "Qualcomm Snapdragon 8 Gen 3 (4nm)",
    processor_cores: "ثماني النواة",
    processor_frequency: "1×3.3 GHz + 3×3.2 GHz + 2×3.0 GHz + 2×2.3 GHz",
    processor_gpu: "Adreno 750",
    processor_fabrication: "4 نانومتر",
    antutu_score: "2,200,000",
    memory_storage: "256/512GB/1TB",
    memory_ram: "12GB",
    memory_type: "UFS 4.0",
    memory_sd_card: "لا",
    camera_main: "50 ميجابكسل، f/1.8، OIS، Dual Pixel PDAF",
    camera_ultrawide: "12 ميجابكسل، f/2.2، زاوية واسعة 123°",
    camera_telephoto: "10 ميجابكسل، f/2.4، تقريب بصري 3×، OIS",
    camera_front: "10 ميجابكسل خارجية، 4 ميجابكسل تحت الشاشة الداخلية",
    camera_video: "8K@30fps، 4K@60fps",
    audio_speakers: "ستيريو من AKG",
    audio_jack: "لا",
    connectivity_sim: "Nano-SIM + eSIM",
    connectivity_network: "5G SA/NSA",
    connectivity_wifi: "Wi-Fi 6E",
    connectivity_bluetooth: "5.3",
    connectivity_nfc: "نعم",
    connectivity_gps: "GPS، GLONASS، Galileo، BeiDou، QZSS",
    protection_water: "IPX8",
    protection_standard: "IPX8 (مقاومة الماء حتى 1.5 متر)",
    battery_capacity: "4400 مللي أمبير",
    battery_charging: "25 واط",
    battery_wireless: "15 واط",
    battery_reverse: "4.5 واط",
    software_os: "Android 14",
    software_ui: "One UI 6.1.1",
    sensor_fingerprint: "جانبي",
    sensor_face_unlock: "نعم",
    sensor_gyroscope: "نعم",
    sensor_compass: "نعم",
    sensor_proximity: "نعم",
    sensor_light: "نعم",
    sensor_other: "مقياس التسارع، البارومتر، Flex Mode"
  },

  // Samsung Galaxy Z Flip 6
  {
    slug: "samsung-galaxy-z-flip6",
    name: "Samsung Galaxy Z Flip 6",
    name_ar: "سامسونج جالاكسي Z فليب 6",
    brand: "Samsung",
    year: 2025,
    release_date: "يوليو 2025",
    image: "https://fdn2.gsmarena.com/vv/bigpic/samsung-galaxy-z-flip6.jpg",
    status: "published",
    quick_screen: "6.7 بوصة داخلية + 3.4 بوصة خارجية",
    quick_processor: "Snapdragon 8 Gen 3",
    quick_camera: "50 ميجابكسل رئيسية",
    quick_front_camera: "10 ميجابكسل",
    quick_memory: "256/512GB مع 12GB رام",
    quick_battery: "4000 مللي أمبير، شحن 25 واط",
    design_height: "165.1 ملم (مفتوح)",
    design_width: "71.9 ملم",
    design_thickness: "6.9 ملم (مفتوح)، 14.9 ملم (مغلق)",
    design_weight: "187 جرام",
    design_materials: "زجاج Gorilla Glass Victus 2، إطار ألمنيوم Armor",
    design_colors: "أصفر، أزرق، أخضر نعناعي، فضي",
    design_frame: "إطار ألمنيوم Armor",
    screen_type: "Dynamic AMOLED 2X",
    screen_size: "6.7 بوصة داخلية، 3.4 بوصة خارجية",
    screen_resolution: "1080 × 2640 بكسل (داخلية)",
    screen_ppi: "426 بكسل لكل بوصة",
    screen_refresh_rate: "120Hz",
    screen_brightness: "2600 نيت",
    screen_protection: "Gorilla Glass Victus 2",
    processor_name: "Qualcomm Snapdragon 8 Gen 3 (4nm)",
    processor_cores: "ثماني النواة",
    processor_frequency: "1×3.3 GHz + 3×3.2 GHz + 2×3.0 GHz + 2×2.3 GHz",
    processor_gpu: "Adreno 750",
    processor_fabrication: "4 نانومتر",
    antutu_score: "2,200,000",
    memory_storage: "256/512GB",
    memory_ram: "12GB",
    memory_type: "UFS 4.0",
    memory_sd_card: "لا",
    camera_main: "50 ميجابكسل، f/1.8، OIS، Dual Pixel PDAF",
    camera_ultrawide: "12 ميجابكسل، f/2.2، زاوية واسعة 123°",
    camera_front: "10 ميجابكسل، f/2.2",
    camera_video: "4K@60fps، 1080p@240fps",
    audio_speakers: "ستيريو",
    audio_jack: "لا",
    connectivity_sim: "Nano-SIM + eSIM",
    connectivity_network: "5G SA/NSA",
    connectivity_wifi: "Wi-Fi 6E",
    connectivity_bluetooth: "5.3",
    connectivity_nfc: "نعم",
    connectivity_gps: "GPS، GLONASS، Galileo، BeiDou",
    protection_water: "IPX8",
    protection_standard: "IPX8",
    battery_capacity: "4000 مللي أمبير",
    battery_charging: "25 واط",
    battery_wireless: "15 واط",
    battery_reverse: "4.5 واط",
    software_os: "Android 14",
    software_ui: "One UI 6.1.1",
    sensor_fingerprint: "جانبي",
    sensor_face_unlock: "نعم",
    sensor_gyroscope: "نعم",
    sensor_compass: "نعم",
    sensor_proximity: "نعم",
    sensor_light: "نعم",
    sensor_other: "مقياس التسارع، Flex Mode"
  },

  // Samsung Galaxy A56
  {
    slug: "samsung-galaxy-a56",
    name: "Samsung Galaxy A56",
    name_ar: "سامسونج جالاكسي A56",
    brand: "Samsung",
    year: 2025,
    release_date: "مارس 2025",
    image: "https://fdn2.gsmarena.com/vv/bigpic/samsung-galaxy-a56.jpg",
    status: "published",
    quick_screen: "6.7 بوصة Super AMOLED، 120Hz",
    quick_processor: "Exynos 1580",
    quick_camera: "50 ميجابكسل رئيسية",
    quick_front_camera: "12 ميجابكسل",
    quick_memory: "128/256GB مع 8/12GB رام",
    quick_battery: "5000 مللي أمبير، شحن 45 واط",
    design_height: "164.2 ملم",
    design_width: "77.3 ملم",
    design_thickness: "8.2 ملم",
    design_weight: "195 جرام",
    design_materials: "زجاج Gorilla Glass Victus+، إطار ألمنيوم",
    design_colors: "أسود، أزرق، رمادي، أخضر ليموني",
    design_frame: "إطار ألمنيوم",
    screen_type: "Super AMOLED",
    screen_size: "6.7 بوصة",
    screen_resolution: "1080 × 2400 بكسل",
    screen_ppi: "393 بكسل لكل بوصة",
    screen_refresh_rate: "120Hz",
    screen_brightness: "1200 نيت",
    screen_protection: "Corning Gorilla Glass Victus+",
    processor_name: "Samsung Exynos 1580 (4nm)",
    processor_cores: "ثماني النواة",
    processor_frequency: "1×2.9 GHz + 3×2.6 GHz + 4×1.95 GHz",
    processor_gpu: "Mali-G720 MC6",
    processor_fabrication: "4 نانومتر",
    antutu_score: "950,000",
    memory_storage: "128/256GB",
    memory_ram: "8/12GB",
    memory_type: "UFS 3.1",
    memory_sd_card: "نعم، حتى 1TB",
    camera_main: "50 ميجابكسل، f/1.8، OIS، PDAF",
    camera_ultrawide: "12 ميجابكسل، f/2.2، زاوية واسعة 123°",
    camera_telephoto: "5 ميجابكسل، f/2.4، ماكرو",
    camera_front: "12 ميجابكسل، f/2.2",
    camera_video: "4K@30fps، 1080p@60fps",
    audio_speakers: "ستيريو",
    audio_jack: "لا",
    connectivity_sim: "Nano-SIM + eSIM أو Dual SIM",
    connectivity_network: "5G SA/NSA",
    connectivity_wifi: "Wi-Fi 6E",
    connectivity_bluetooth: "5.3",
    connectivity_nfc: "نعم",
    connectivity_gps: "GPS، GLONASS، Galileo، BeiDou",
    protection_water: "IP67",
    protection_standard: "IP67",
    battery_capacity: "5000 مللي أمبير",
    battery_charging: "45 واط",
    battery_wireless: "لا",
    battery_reverse: "لا",
    software_os: "Android 15",
    software_ui: "One UI 7",
    sensor_fingerprint: "بصري تحت الشاشة",
    sensor_face_unlock: "نعم",
    sensor_gyroscope: "نعم",
    sensor_compass: "نعم",
    sensor_proximity: "نعم",
    sensor_light: "نعم",
    sensor_other: "مقياس التسارع"
  },

  // Samsung Galaxy A36
  {
    slug: "samsung-galaxy-a36",
    name: "Samsung Galaxy A36",
    name_ar: "سامسونج جالاكسي A36",
    brand: "Samsung",
    year: 2025,
    release_date: "أبريل 2025",
    image: "https://fdn2.gsmarena.com/vv/bigpic/samsung-galaxy-a36.jpg",
    status: "published",
    quick_screen: "6.6 بوصة Super AMOLED، 120Hz",
    quick_processor: "Snapdragon 6 Gen 3",
    quick_camera: "50 ميجابكسل رئيسية",
    quick_front_camera: "13 ميجابكسل",
    quick_memory: "128/256GB مع 6/8GB رام",
    quick_battery: "5000 مللي أمبير، شحن 25 واط",
    design_height: "162.8 ملم",
    design_width: "76.5 ملم",
    design_thickness: "7.4 ملم",
    design_weight: "185 جرام",
    design_materials: "زجاج Gorilla Glass، إطار بلاستيك",
    design_colors: "أسود، أزرق، أخضر، بنفسجي",
    design_frame: "إطار بلاستيك",
    screen_type: "Super AMOLED",
    screen_size: "6.6 بوصة",
    screen_resolution: "1080 × 2400 بكسل",
    screen_ppi: "399 بكسل لكل بوصة",
    screen_refresh_rate: "120Hz",
    screen_brightness: "1100 نيت",
    screen_protection: "Corning Gorilla Glass 5",
    processor_name: "Qualcomm Snapdragon 6 Gen 3 (4nm)",
    processor_cores: "ثماني النواة",
    processor_frequency: "4×2.4 GHz + 4×1.8 GHz",
    processor_gpu: "Adreno 710",
    processor_fabrication: "4 نانومتر",
    antutu_score: "620,000",
    memory_storage: "128/256GB",
    memory_ram: "6/8GB",
    memory_type: "UFS 2.2",
    memory_sd_card: "نعم، حتى 1TB",
    camera_main: "50 ميجابكسل، f/1.8، OIS، PDAF",
    camera_ultrawide: "8 ميجابكسل، f/2.2، زاوية واسعة 120°",
    camera_telephoto: "5 ميجابكسل، f/2.4، ماكرو",
    camera_front: "13 ميجابكسل، f/2.2",
    camera_video: "4K@30fps، 1080p@60fps",
    audio_speakers: "ستيريو",
    audio_jack: "لا",
    connectivity_sim: "Nano-SIM + Nano-SIM أو eSIM",
    connectivity_network: "5G SA/NSA",
    connectivity_wifi: "Wi-Fi 6",
    connectivity_bluetooth: "5.3",
    connectivity_nfc: "نعم",
    connectivity_gps: "GPS، GLONASS، Galileo، BeiDou",
    protection_water: "IP54",
    protection_standard: "IP54",
    battery_capacity: "5000 مللي أمبير",
    battery_charging: "25 واط",
    battery_wireless: "لا",
    battery_reverse: "لا",
    software_os: "Android 15",
    software_ui: "One UI 7",
    sensor_fingerprint: "بصري تحت الشاشة",
    sensor_face_unlock: "نعم",
    sensor_gyroscope: "نعم",
    sensor_compass: "نعم",
    sensor_proximity: "نعم",
    sensor_light: "نعم",
    sensor_other: "مقياس التسارع"
  },

  // ==================== SAMSUNG 2026 ====================

  // Samsung Galaxy S26 Ultra
  {
    slug: "samsung-galaxy-s26-ultra",
    name: "Samsung Galaxy S26 Ultra",
    name_ar: "سامسونج جالاكسي S26 ألترا",
    brand: "Samsung",
    year: 2026,
    release_date: "مارس 2026",
    image: "https://fdn2.gsmarena.com/vv/bigpic/samsung-galaxy-s26-ultra.jpg",
    status: "published",
    quick_screen: "6.9 بوصة Dynamic LTPO AMOLED 2X، 120Hz",
    quick_processor: "Snapdragon 8 Elite Gen 5",
    quick_camera: "200 ميجابكسل رئيسية",
    quick_front_camera: "12 ميجابكسل",
    quick_memory: "256/512GB/1TB مع 12/16GB رام",
    quick_battery: "5000 مللي أمبير، شحن 60 واط",
    design_height: "163.6 ملم",
    design_width: "78.1 ملم",
    design_thickness: "7.9 ملم",
    design_weight: "214 جرام",
    design_materials: "زجاج Gorilla Armor 2، إطار Armor Aluminum 2",
    design_colors: "بنفسجي كوبالت، أزرق سماوي، أسود، أبيض، فضي ظل، وردي ذهبي",
    design_frame: "إطار Armor Aluminum 2",
    screen_type: "Dynamic LTPO AMOLED 2X",
    screen_size: "6.9 بوصة",
    screen_resolution: "1440 × 3120 بكسل",
    screen_ppi: "500 بكسل لكل بوصة",
    screen_refresh_rate: "120Hz",
    screen_touch_rate: "480Hz",
    screen_brightness: "2600 نيت (ذروة)",
    screen_protection: "Corning Gorilla Armor 2، طبقة DX مضادة للانعكاس",
    screen_back_protection: "Gorilla Glass Victus 2",
    processor_name: "Qualcomm Snapdragon 8 Elite Gen 5 (3nm)",
    processor_cores: "ثماني النواة",
    processor_frequency: "2×4.74 GHz Oryon V3 + 6×3.62 GHz Oryon V3",
    processor_gpu: "Adreno 840 (1.3GHz)",
    processor_fabrication: "3 نانومتر",
    antutu_score: "3,890,000",
    memory_storage: "256/512GB/1TB",
    memory_ram: "12GB/16GB",
    memory_type: "UFS 4.X",
    memory_sd_card: "لا",
    camera_main: "200 ميجابكسل، f/1.4، OIS، PDAF متعدد الاتجاهات",
    camera_ultrawide: "50 ميجابكسل، f/1.9، زاوية فائقة الاتساع 120°، Dual Pixel PDAF",
    camera_telephoto: "50 ميجابكسل، f/2.9، تقريب بصري 5× بيريسكوب + 10 ميجابكسل، f/2.4، تقريب بصري 3×",
    camera_macro: "دمج في الكاميرا الرئيسية",
    camera_front: "12 ميجابكسل، f/2.2، Dual Pixel PDAF",
    camera_video: "8K@24/30fps، 4K@30/60/120fps، 10-bit HDR، HDR10+",
    audio_speakers: "ستيريو، دعم صوت عالي الدقة",
    audio_jack: "لا",
    connectivity_sim: "Nano-SIM + Nano-SIM + eSIM (حتى 2 في نفس الوقت)",
    connectivity_network: "5G SA/NSA/Sub6/mmWave",
    connectivity_wifi: "Wi-Fi 7 (802.11be) ثلاثي النطاق",
    connectivity_bluetooth: "6.0",
    connectivity_nfc: "نعم",
    connectivity_gps: "GPS، GLONASS، Galileo، BeiDou، QZSS",
    protection_water: "IP68",
    protection_standard: "IP68 (مقاومة الماء حتى 1.5 متر لمدة 30 دقيقة)",
    battery_capacity: "5000 مللي أمبير",
    battery_charging: "60 واط سلكي، 75% في 30 دقيقة",
    battery_wireless: "25 واط Qi2.2",
    battery_reverse: "4.5 واط عكسي لاسلكي",
    software_os: "Android 16",
    software_ui: "One UI 8.5",
    sensor_fingerprint: "بالموجات فوق الصوتية تحت الشاشة",
    sensor_face_unlock: "نعم",
    sensor_gyroscope: "نعم",
    sensor_compass: "نعم",
    sensor_proximity: "نعم",
    sensor_light: "نعم",
    sensor_other: "مقياس التسارع، البارومتر، S Pen، UWB، Samsung DeX"
  },

  // Samsung Galaxy S26+
  {
    slug: "samsung-galaxy-s26-plus",
    name: "Samsung Galaxy S26+",
    name_ar: "سامسونج جالاكسي S26 بلس",
    brand: "Samsung",
    year: 2026,
    release_date: "مارس 2026",
    image: "https://fdn2.gsmarena.com/vv/bigpic/samsung-galaxy-s26-plus.jpg",
    status: "published",
    quick_screen: "6.7 بوصة Dynamic AMOLED 2X، 120Hz",
    quick_processor: "Snapdragon 8 Elite Gen 5",
    quick_camera: "50 ميجابكسل رئيسية",
    quick_front_camera: "12 ميجابكسل",
    quick_memory: "256/512GB مع 12GB رام",
    quick_battery: "4900 مللي أمبير، شحن 60 واط",
    design_height: "158.4 ملم",
    design_width: "75.8 ملم",
    design_thickness: "7.2 ملم",
    design_weight: "188 جرام",
    design_materials: "زجاج Gorilla Glass Victus 3، إطار ألمنيوم",
    design_colors: "أسود، أبيض، أزرق سماوي، فضي",
    design_frame: "إطار ألمنيوم",
    screen_type: "Dynamic AMOLED 2X",
    screen_size: "6.7 بوصة",
    screen_resolution: "1440 × 3120 بكسل",
    screen_ppi: "513 بكسل لكل بوصة",
    screen_refresh_rate: "120Hz",
    screen_brightness: "2600 نيت",
    screen_protection: "Corning Gorilla Glass Victus 3",
    processor_name: "Qualcomm Snapdragon 8 Elite Gen 5 (3nm)",
    processor_cores: "ثماني النواة",
    processor_frequency: "2×4.74 GHz + 6×3.62 GHz",
    processor_gpu: "Adreno 840",
    processor_fabrication: "3 نانومتر",
    antutu_score: "3,890,000",
    memory_storage: "256/512GB",
    memory_ram: "12GB",
    memory_type: "UFS 4.X",
    memory_sd_card: "لا",
    camera_main: "50 ميجابكسل، f/1.8، OIS، Dual Pixel PDAF",
    camera_ultrawide: "12 ميجابكسل، f/2.2، زاوية واسعة 120°",
    camera_telephoto: "10 ميجابكسل، f/2.4، تقريب بصري 3×، OIS",
    camera_front: "12 ميجابكسل، f/2.2",
    camera_video: "8K@30fps، 4K@60fps، HDR10+",
    audio_speakers: "ستيريو",
    audio_jack: "لا",
    connectivity_sim: "Nano-SIM + eSIM",
    connectivity_network: "5G SA/NSA",
    connectivity_wifi: "Wi-Fi 7",
    connectivity_bluetooth: "6.0",
    connectivity_nfc: "نعم",
    connectivity_gps: "GPS، GLONASS، Galileo، BeiDou، QZSS",
    protection_water: "IP68",
    protection_standard: "IP68",
    battery_capacity: "4900 مللي أمبير",
    battery_charging: "60 واط",
    battery_wireless: "25 واط",
    battery_reverse: "4.5 واط",
    software_os: "Android 16",
    software_ui: "One UI 8.5",
    sensor_fingerprint: "بالموجات فوق الصوتية تحت الشاشة",
    sensor_face_unlock: "نعم",
    sensor_gyroscope: "نعم",
    sensor_compass: "نعم",
    sensor_proximity: "نعم",
    sensor_light: "نعم",
    sensor_other: "مقياس التسارع، البارومتر"
  },

  // Samsung Galaxy S26
  {
    slug: "samsung-galaxy-s26",
    name: "Samsung Galaxy S26",
    name_ar: "سامسونج جالاكسي S26",
    brand: "Samsung",
    year: 2026,
    release_date: "مارس 2026",
    image: "https://fdn2.gsmarena.com/vv/bigpic/samsung-galaxy-s26.jpg",
    status: "published",
    quick_screen: "6.2 بوصة Dynamic AMOLED 2X، 120Hz",
    quick_processor: "Snapdragon 8 Elite Gen 5",
    quick_camera: "50 ميجابكسل رئيسية",
    quick_front_camera: "12 ميجابكسل",
    quick_memory: "128/256/512GB مع 12GB رام",
    quick_battery: "4000 مللي أمبير، شحن 45 واط",
    design_height: "146.5 ملم",
    design_width: "70.2 ملم",
    design_thickness: "7.1 ملم",
    design_weight: "160 جرام",
    design_materials: "زجاج Gorilla Glass Victus 3، إطار ألمنيوم",
    design_colors: "أسود، أبيض، أزرق، أخضر نعناعي",
    design_frame: "إطار ألمنيوم",
    screen_type: "Dynamic AMOLED 2X",
    screen_size: "6.2 بوصة",
    screen_resolution: "1080 × 2340 بكسل",
    screen_ppi: "416 بكسل لكل بوصة",
    screen_refresh_rate: "120Hz",
    screen_brightness: "2600 نيت",
    screen_protection: "Corning Gorilla Glass Victus 3",
    processor_name: "Qualcomm Snapdragon 8 Elite Gen 5 (3nm)",
    processor_cores: "ثماني النواة",
    processor_frequency: "2×4.74 GHz + 6×3.62 GHz",
    processor_gpu: "Adreno 840",
    processor_fabrication: "3 نانومتر",
    antutu_score: "3,890,000",
    memory_storage: "128/256/512GB",
    memory_ram: "12GB",
    memory_type: "UFS 4.X",
    memory_sd_card: "لا",
    camera_main: "50 ميجابكسل، f/1.8، OIS، Dual Pixel PDAF",
    camera_ultrawide: "12 ميجابكسل، f/2.2، زاوية واسعة 120°",
    camera_telephoto: "10 ميجابكسل، f/2.4، تقريب بصري 3×",
    camera_front: "12 ميجابكسل، f/2.2",
    camera_video: "8K@30fps، 4K@60fps",
    audio_speakers: "ستيريو",
    audio_jack: "لا",
    connectivity_sim: "Nano-SIM + eSIM",
    connectivity_network: "5G SA/NSA",
    connectivity_wifi: "Wi-Fi 7",
    connectivity_bluetooth: "6.0",
    connectivity_nfc: "نعم",
    connectivity_gps: "GPS، GLONASS، Galileo، BeiDou",
    protection_water: "IP68",
    protection_standard: "IP68",
    battery_capacity: "4000 مللي أمبير",
    battery_charging: "45 واط",
    battery_wireless: "25 واط",
    battery_reverse: "4.5 واط",
    software_os: "Android 16",
    software_ui: "One UI 8.5",
    sensor_fingerprint: "بالموجات فوق الصوتية تحت الشاشة",
    sensor_face_unlock: "نعم",
    sensor_gyroscope: "نعم",
    sensor_compass: "نعم",
    sensor_proximity: "نعم",
    sensor_light: "نعم",
    sensor_other: "مقياس التسارع، البارومتر"
  },

  // Samsung Galaxy Z Fold 7
  {
    slug: "samsung-galaxy-z-fold7",
    name: "Samsung Galaxy Z Fold 7",
    name_ar: "سامسونج جالاكسي Z فولد 7",
    brand: "Samsung",
    year: 2026,
    release_date: "يوليو 2026",
    image: "https://fdn2.gsmarena.com/vv/bigpic/samsung-galaxy-z-fold7.jpg",
    status: "published",
    quick_screen: "8.0 بوصة داخلية + 6.5 بوصة خارجية",
    quick_processor: "Snapdragon 8 Elite Gen 5",
    quick_camera: "50 ميجابكسل رئيسية",
    quick_front_camera: "12 ميجابكسل",
    quick_memory: "256/512GB/1TB مع 12/16GB رام",
    quick_battery: "4800 مللي أمبير، شحن 45 واط",
    design_height: "155 ملم (مفتوح)",
    design_width: "135 ملم (مفتوح)",
    design_thickness: "5.4 ملم (مفتوح)، 11 ملم (مغلق)",
    design_weight: "225 جرام",
    design_materials: "زجاج Gorilla Glass Victus 3، إطار ألمنيوم Armor",
    design_colors: "أسود، أزرق، فضي، وردي ذهبي",
    design_frame: "إطار ألمنيوم Armor",
    screen_type: "Dynamic AMOLED 2X",
    screen_size: "8.0 بوصة داخلية، 6.5 بوصة خارجية",
    screen_resolution: "2200 × 1900 بكسل (داخلية)",
    screen_ppi: "385 بكسل لكل بوصة",
    screen_refresh_rate: "120Hz",
    screen_brightness: "2600 نيت",
    screen_protection: "Gorilla Glass Victus 3",
    processor_name: "Qualcomm Snapdragon 8 Elite Gen 5 (3nm)",
    processor_cores: "ثماني النواة",
    processor_frequency: "2×4.74 GHz + 6×3.62 GHz",
    processor_gpu: "Adreno 840",
    processor_fabrication: "3 نانومتر",
    antutu_score: "3,850,000",
    memory_storage: "256/512GB/1TB",
    memory_ram: "12GB/16GB",
    memory_type: "UFS 4.X",
    memory_sd_card: "لا",
    camera_main: "50 ميجابكسل، f/1.8، OIS، PDAF",
    camera_ultrawide: "12 ميجابكسل، f/2.2، زاوية واسعة 123°",
    camera_telephoto: "12 ميجابكسل، f/2.4، تقريب بصري 3×، OIS",
    camera_front: "12 ميجابكسل خارجية، 4 ميجابكسل تحت الشاشة",
    camera_video: "8K@30fps، 4K@60fps",
    audio_speakers: "ستيريو",
    audio_jack: "لا",
    connectivity_sim: "eSIM + eSIM",
    connectivity_network: "5G SA/NSA",
    connectivity_wifi: "Wi-Fi 7",
    connectivity_bluetooth: "6.0",
    connectivity_nfc: "نعم",
    connectivity_gps: "GPS، GLONASS، Galileo، BeiDou",
    protection_water: "IPX8",
    protection_standard: "IPX8",
    battery_capacity: "4800 مللي أمبير",
    battery_charging: "45 واط",
    battery_wireless: "25 واط",
    battery_reverse: "4.5 واط",
    software_os: "Android 16",
    software_ui: "One UI 8",
    sensor_fingerprint: "جانبي",
    sensor_face_unlock: "نعم",
    sensor_gyroscope: "نعم",
    sensor_compass: "نعم",
    sensor_proximity: "نعم",
    sensor_light: "نعم",
    sensor_other: "مقياس التسارع، البارومتر، Flex Mode"
  },

  // ==================== APPLE 2025 ====================

  // iPhone 16 Pro Max
  {
    slug: "apple-iphone-16-pro-max",
    name: "Apple iPhone 16 Pro Max",
    name_ar: "آبل آيفون 16 برو ماكس",
    brand: "Apple",
    year: 2025,
    release_date: "سبتمبر 2024",
    image: "https://fdn2.gsmarena.com/vv/bigpic/apple-iphone-16-pro-max.jpg",
    status: "published",
    quick_screen: "6.9 بوصة Super Retina XDR، 120Hz",
    quick_processor: "Apple A18 Pro",
    quick_camera: "48 ميجابكسل رئيسية",
    quick_front_camera: "12 ميجابكسل",
    quick_memory: "256/512GB/1TB مع 8GB رام",
    quick_battery: "4685 مللي أمبير، شحن 40 واط",
    design_height: "163.0 ملم",
    design_width: "77.6 ملم",
    design_thickness: "8.25 ملم",
    design_weight: "227 جرام",
    design_materials: "زجاج Ceramic Shield، إطار من التيتانيوم",
    design_colors: "تيتانيوم صحراوي، تيتانيوم طبيعي، تيتانيوم أبيض، تيتانيوم أسود",
    design_frame: "إطار من التيتانيوم من الدرجة 5",
    screen_type: "Super Retina XDR OLED، LTPO",
    screen_size: "6.9 بوصة",
    screen_resolution: "1320 × 2868 بكسل",
    screen_ppi: "460 بكسل لكل بوصة",
    screen_refresh_rate: "1-120Hz (ProMotion)",
    screen_brightness: "2000 نيت (HDR)، 1000 نيت (عادي)",
    screen_protection: "Ceramic Shield",
    processor_name: "Apple A18 Pro (3nm)",
    processor_cores: "سداسي النواة",
    processor_frequency: "2×4.05 GHz + 4×2.42 GHz",
    processor_gpu: "Apple GPU (6 أنوية)",
    processor_fabrication: "3 نانومتر",
    antutu_score: "2,700,000",
    memory_storage: "256/512GB/1TB",
    memory_ram: "8GB",
    memory_type: "NVMe",
    memory_sd_card: "لا",
    camera_main: "48 ميجابكسل، f/1.78، OIS، Sensor-shift",
    camera_ultrawide: "48 ميجابكسل، f/2.2، زاوية واسعة 120°",
    camera_telephoto: "12 ميجابكسل، f/2.8، تقريب بصري 5×، OIS",
    camera_front: "12 ميجابكسل، f/1.9، autofocus",
    camera_video: "4K@120fps، ProRes، Dolby Vision، Cinematic mode 4K",
    audio_speakers: "ستيريو",
    audio_jack: "لا",
    connectivity_sim: "نانو سيم + eSIM (دعم ثنائي eSIM)",
    connectivity_network: "5G SA/NSA",
    connectivity_wifi: "Wi-Fi 6E",
    connectivity_bluetooth: "5.3",
    connectivity_nfc: "نعم",
    connectivity_gps: "GPS، GLONASS، Galileo، QZSS، BeiDou",
    protection_water: "IP68",
    protection_standard: "IP68 (حتى 6 أمتار لمدة 30 دقيقة)",
    battery_capacity: "4685 مللي أمبير",
    battery_charging: "40 واط سلكي (USB-C)، MagSafe 25 واط",
    battery_wireless: "25 واط MagSafe",
    battery_reverse: "لا",
    software_os: "iOS 18",
    software_ui: "iOS 18",
    sensor_fingerprint: "لا",
    sensor_face_unlock: "Face ID (3D)",
    sensor_gyroscope: "نعم",
    sensor_compass: "نعم",
    sensor_proximity: "نعم",
    sensor_light: "نعم",
    sensor_other: "مقياس التسارع، البارومتر، LiDAR Scanner، Ultra Wideband (UWB)"
  },

  // iPhone 16 Pro
  {
    slug: "apple-iphone-16-pro",
    name: "Apple iPhone 16 Pro",
    name_ar: "آبل آيفون 16 برو",
    brand: "Apple",
    year: 2025,
    release_date: "سبتمبر 2024",
    image: "https://fdn2.gsmarena.com/vv/bigpic/apple-iphone-16-pro.jpg",
    status: "published",
    quick_screen: "6.3 بوصة Super Retina XDR، 120Hz",
    quick_processor: "Apple A18 Pro",
    quick_camera: "48 ميجابكسل رئيسية",
    quick_front_camera: "12 ميجابكسل",
    quick_memory: "128/256/512GB/1TB مع 8GB رام",
    quick_battery: "3582 مللي أمبير، شحن 40 واط",
    design_height: "149.6 ملم",
    design_width: "71.5 ملم",
    design_thickness: "8.25 ملم",
    design_weight: "199 جرام",
    design_materials: "زجاج Ceramic Shield، إطار من التيتانيوم",
    design_colors: "تيتانيوم صحراوي، تيتانيوم طبيعي، تيتانيوم أبيض، تيتانيوم أسود",
    design_frame: "إطار من التيتانيوم",
    screen_type: "Super Retina XDR OLED، LTPO",
    screen_size: "6.3 بوصة",
    screen_resolution: "1206 × 2622 بكسل",
    screen_ppi: "460 بكسل لكل بوصة",
    screen_refresh_rate: "1-120Hz (ProMotion)",
    screen_brightness: "2000 نيت",
    screen_protection: "Ceramic Shield",
    processor_name: "Apple A18 Pro (3nm)",
    processor_cores: "سداسي النواة",
    processor_frequency: "2×4.05 GHz + 4×2.42 GHz",
    processor_gpu: "Apple GPU (6 أنوية)",
    processor_fabrication: "3 نانومتر",
    antutu_score: "2,700,000",
    memory_storage: "128/256/512GB/1TB",
    memory_ram: "8GB",
    memory_type: "NVMe",
    memory_sd_card: "لا",
    camera_main: "48 ميجابكسل، f/1.78، OIS، Sensor-shift",
    camera_ultrawide: "48 ميجابكسل، f/2.2، زاوية واسعة 120°",
    camera_telephoto: "12 ميجابكسل، f/2.8، تقريب بصري 5×، OIS",
    camera_front: "12 ميجابكسل، f/1.9، autofocus",
    camera_video: "4K@120fps، ProRes، Dolby Vision",
    audio_speakers: "ستيريو",
    audio_jack: "لا",
    connectivity_sim: "نانو سيم + eSIM",
    connectivity_network: "5G SA/NSA",
    connectivity_wifi: "Wi-Fi 6E",
    connectivity_bluetooth: "5.3",
    connectivity_nfc: "نعم",
    connectivity_gps: "GPS، GLONASS، Galileo، QZSS، BeiDou",
    protection_water: "IP68",
    protection_standard: "IP68 (حتى 6 أمتار)",
    battery_capacity: "3582 مللي أمبير",
    battery_charging: "40 واط",
    battery_wireless: "25 واط MagSafe",
    battery_reverse: "لا",
    software_os: "iOS 18",
    software_ui: "iOS 18",
    sensor_fingerprint: "لا",
    sensor_face_unlock: "Face ID",
    sensor_gyroscope: "نعم",
    sensor_compass: "نعم",
    sensor_proximity: "نعم",
    sensor_light: "نعم",
    sensor_other: "مقياس التسارع، البارومتر، LiDAR Scanner"
  },

  // iPhone 16
  {
    slug: "apple-iphone-16",
    name: "Apple iPhone 16",
    name_ar: "آبل آيفون 16",
    brand: "Apple",
    year: 2025,
    release_date: "سبتمبر 2024",
    image: "https://fdn2.gsmarena.com/vv/bigpic/apple-iphone-16.jpg",
    status: "published",
    quick_screen: "6.1 بوصة Super Retina XDR، 60Hz",
    quick_processor: "Apple A18",
    quick_camera: "48 ميجابكسل رئيسية",
    quick_front_camera: "12 ميجابكسل",
    quick_memory: "128/256/512GB مع 8GB رام",
    quick_battery: "3561 مللي أمبير، شحن 30 واط",
    design_height: "147.6 ملم",
    design_width: "71.6 ملم",
    design_thickness: "7.8 ملم",
    design_weight: "170 جرام",
    design_materials: "زجاج Ceramic Shield، إطار ألمنيوم",
    design_colors: "أزرق، وردي، أسود، أبيض، أخضر",
    design_frame: "إطار ألمنيوم",
    screen_type: "Super Retina XDR OLED",
    screen_size: "6.1 بوصة",
    screen_resolution: "1179 × 2556 بكسل",
    screen_ppi: "460 بكسل لكل بوصة",
    screen_refresh_rate: "60Hz",
    screen_brightness: "2000 نيت",
    screen_protection: "Ceramic Shield",
    processor_name: "Apple A18 (3nm)",
    processor_cores: "سداسي النواة",
    processor_frequency: "2×4.0 GHz + 4×2.0 GHz",
    processor_gpu: "Apple GPU (5 أنوية)",
    processor_fabrication: "3 نانومتر",
    antutu_score: "2,400,000",
    memory_storage: "128/256/512GB",
    memory_ram: "8GB",
    memory_type: "NVMe",
    memory_sd_card: "لا",
    camera_main: "48 ميجابكسل، f/1.6، OIS",
    camera_ultrawide: "12 ميجابكسل، f/2.2، زاوية واسعة 120°",
    camera_front: "12 ميجابكسل، f/1.9، autofocus",
    camera_video: "4K@60fps، Dolby Vision، Cinematic mode",
    audio_speakers: "ستيريو",
    audio_jack: "لا",
    connectivity_sim: "نانو سيم + eSIM",
    connectivity_network: "5G SA/NSA",
    connectivity_wifi: "Wi-Fi 6E",
    connectivity_bluetooth: "5.3",
    connectivity_nfc: "نعم",
    connectivity_gps: "GPS، GLONASS، Galileo، BeiDou",
    protection_water: "IP68",
    protection_standard: "IP68 (حتى 6 أمتار)",
    battery_capacity: "3561 مللي أمبير",
    battery_charging: "30 واط",
    battery_wireless: "15 واط MagSafe",
    battery_reverse: "لا",
    software_os: "iOS 18",
    software_ui: "iOS 18",
    sensor_fingerprint: "لا",
    sensor_face_unlock: "Face ID",
    sensor_gyroscope: "نعم",
    sensor_compass: "نعم",
    sensor_proximity: "نعم",
    sensor_light: "نعم",
    sensor_other: "مقياس التسارع، البارومتر"
  },

  // ==================== APPLE 2026 ====================

  // iPhone 17 Pro Max
  {
    slug: "apple-iphone-17-pro-max",
    name: "Apple iPhone 17 Pro Max",
    name_ar: "آبل آيفون 17 برو ماكس",
    brand: "Apple",
    year: 2026,
    release_date: "سبتمبر 2025",
    image: "https://fdn2.gsmarena.com/vv/bigpic/apple-iphone-17-pro-max.jpg",
    status: "published",
    quick_screen: "6.9 بوصة Super Retina XDR، 120Hz",
    quick_processor: "Apple A19 Pro",
    quick_camera: "48 ميجابكسل Pro Fusion",
    quick_front_camera: "18 ميجابكسل Center Stage",
    quick_memory: "256/512GB/1TB/2TB مع 12GB رام",
    quick_battery: "4900 مللي أمبير، شحن 50 واط",
    design_height: "164.0 ملم",
    design_width: "78.0 ملم",
    design_thickness: "8.1 ملم",
    design_weight: "233 جرام",
    design_materials: "Ceramic Shield 2، إطار ألمنيوم Unibody",
    design_colors: "فضي، برتقالي كوني، أزرق عميق",
    design_frame: "ألمنيوم Unibody",
    screen_type: "Super Retina XDR OLED، LTPO",
    screen_size: "6.9 بوصة",
    screen_resolution: "1320 × 2868 بكسل",
    screen_ppi: "460 بكسل لكل بوصة",
    screen_refresh_rate: "1-120Hz (ProMotion)",
    screen_brightness: "3000 نيت (ذروة خارجية)، 1600 نيت (HDR)",
    screen_protection: "Ceramic Shield 2",
    processor_name: "Apple A19 Pro (2nm)",
    processor_cores: "سداسي النواة",
    processor_frequency: "2×4.5 GHz + 4×2.8 GHz",
    processor_gpu: "Apple GPU (8 أنوية)، Neural Engine 18 نواة",
    processor_fabrication: "2 نانومتر",
    antutu_score: "3,500,000",
    memory_storage: "256/512GB/1TB/2TB",
    memory_ram: "12GB",
    memory_type: "NVMe",
    memory_sd_card: "لا",
    camera_main: "48 ميجابكسل Pro Fusion، f/1.78، OIS، تقريب بصري 2×",
    camera_ultrawide: "48 ميجابكسل Fusion Ultra Wide، f/2.2، 120°",
    camera_telephoto: "48 ميجابكسل Fusion Telephoto 4×، f/2.8 + تقريب 8× optical-quality",
    camera_front: "18 ميجابكسل Center Stage، f/1.9",
    camera_video: "4K Dolby Vision@120fps، ProRes RAW، Spatial Video، Apple Log 2",
    audio_speakers: "ستيريو، Spatial Audio",
    audio_jack: "لا",
    connectivity_sim: "Dual eSIM (حتى 8 eSIMs)",
    connectivity_network: "5G SA/NSA/mmWave",
    connectivity_wifi: "Wi-Fi 7 (802.11be) 2x2 MIMO",
    connectivity_bluetooth: "6.0",
    connectivity_nfc: "نعم",
    connectivity_gps: "GPS، GLONASS، Galileo، QZSS، BeiDou، NavIC",
    protection_water: "IP68",
    protection_standard: "IP68 (حتى 6 أمتار لمدة 30 دقيقة)",
    battery_capacity: "4900 مللي أمبير",
    battery_charging: "50 واط سلكي (50% في 20 دقيقة)، 25 واط MagSafe",
    battery_wireless: "25 واط MagSafe/Qi2",
    battery_reverse: "لا",
    software_os: "iOS 26",
    software_ui: "iOS 26",
    sensor_fingerprint: "لا",
    sensor_face_unlock: "Face ID (TrueDepth)",
    sensor_gyroscope: "نعم",
    sensor_compass: "نعم",
    sensor_proximity: "نعم",
    sensor_light: "Dual ambient light",
    sensor_other: "LiDAR Scanner، UWB Gen 2، البارومتر، Crash Detection"
  },

  // iPhone 17 Pro
  {
    slug: "apple-iphone-17-pro",
    name: "Apple iPhone 17 Pro",
    name_ar: "آبل آيفون 17 برو",
    brand: "Apple",
    year: 2026,
    release_date: "سبتمبر 2025",
    image: "https://fdn2.gsmarena.com/vv/bigpic/apple-iphone-17-pro.jpg",
    status: "published",
    quick_screen: "6.3 بوصة Super Retina XDR، 120Hz",
    quick_processor: "Apple A19 Pro",
    quick_camera: "48 ميجابكسل Pro Fusion",
    quick_front_camera: "18 ميجابكسل",
    quick_memory: "256/512GB/1TB مع 12GB رام",
    quick_battery: "3800 مللي أمبير، شحن 50 واط",
    design_height: "150.0 ملم",
    design_width: "71.8 ملم",
    design_thickness: "8.1 ملم",
    design_weight: "206 جرام",
    design_materials: "Ceramic Shield 2، إطار ألمنيوم Unibody",
    design_colors: "فضي، برتقالي كوني، أزرق عميق",
    design_frame: "ألمنيوم Unibody",
    screen_type: "Super Retina XDR OLED، LTPO",
    screen_size: "6.3 بوصة",
    screen_resolution: "1206 × 2622 بكسل",
    screen_ppi: "460 بكسل لكل بوصة",
    screen_refresh_rate: "1-120Hz (ProMotion)",
    screen_brightness: "3000 نيت (ذروة)",
    screen_protection: "Ceramic Shield 2",
    processor_name: "Apple A19 Pro (2nm)",
    processor_cores: "سداسي النواة",
    processor_frequency: "2×4.5 GHz + 4×2.8 GHz",
    processor_gpu: "Apple GPU (8 أنوية)",
    processor_fabrication: "2 نانومتر",
    antutu_score: "3,500,000",
    memory_storage: "256/512GB/1TB",
    memory_ram: "12GB",
    memory_type: "NVMe",
    memory_sd_card: "لا",
    camera_main: "48 ميجابكسل Pro Fusion، f/1.78، OIS",
    camera_ultrawide: "48 ميجابكسل، f/2.2، 120°",
    camera_telephoto: "48 ميجابكسل، f/2.8، تقريب بصري 4×",
    camera_front: "18 ميجابكسل، f/1.9",
    camera_video: "4K Dolby Vision@120fps، ProRes RAW",
    audio_speakers: "ستيريو",
    audio_jack: "لا",
    connectivity_sim: "Dual eSIM",
    connectivity_network: "5G SA/NSA/mmWave",
    connectivity_wifi: "Wi-Fi 7",
    connectivity_bluetooth: "6.0",
    connectivity_nfc: "نعم",
    connectivity_gps: "GPS، GLONASS، Galileo، BeiDou، NavIC",
    protection_water: "IP68",
    protection_standard: "IP68 (حتى 6 أمتار)",
    battery_capacity: "3800 مللي أمبير",
    battery_charging: "50 واط",
    battery_wireless: "25 واط MagSafe",
    battery_reverse: "لا",
    software_os: "iOS 26",
    software_ui: "iOS 26",
    sensor_fingerprint: "لا",
    sensor_face_unlock: "Face ID",
    sensor_gyroscope: "نعم",
    sensor_compass: "نعم",
    sensor_proximity: "نعم",
    sensor_light: "نعم",
    sensor_other: "LiDAR Scanner، UWB"
  },

  // iPhone 17e
  {
    slug: "apple-iphone-17e",
    name: "Apple iPhone 17e",
    name_ar: "آبل آيفون 17e",
    brand: "Apple",
    year: 2026,
    release_date: "مارس 2026",
    image: "https://fdn2.gsmarena.com/vv/bigpic/apple-iphone-17e.jpg",
    status: "published",
    quick_screen: "6.1 بوصة Super Retina XDR، 60Hz",
    quick_processor: "Apple A18",
    quick_camera: "48 ميجابكسل Fusion",
    quick_front_camera: "12 ميجابكسل",
    quick_memory: "128/256/512GB مع 8GB رام",
    quick_battery: "3500 مللي أمبير، شحن 30 واط",
    design_height: "147.5 ملم",
    design_width: "71.5 ملم",
    design_thickness: "7.8 ملم",
    design_weight: "165 جرام",
    design_materials: "Ceramic Shield، إطار ألمنيوم",
    design_colors: "أسود، أبيض، أزرق، أخضر، وردي",
    design_frame: "إطار ألمنيوم",
    screen_type: "Super Retina XDR OLED",
    screen_size: "6.1 بوصة",
    screen_resolution: "1170 × 2532 بكسل",
    screen_ppi: "460 بكسل لكل بوصة",
    screen_refresh_rate: "60Hz",
    screen_brightness: "2000 نيت",
    screen_protection: "Ceramic Shield",
    processor_name: "Apple A18 (3nm)",
    processor_cores: "سداسي النواة",
    processor_frequency: "2×4.0 GHz + 4×2.0 GHz",
    processor_gpu: "Apple GPU (5 أنوية)",
    processor_fabrication: "3 نانومتر",
    antutu_score: "2,400,000",
    memory_storage: "128/256/512GB",
    memory_ram: "8GB",
    memory_type: "NVMe",
    memory_sd_card: "لا",
    camera_main: "48 ميجابكسل Fusion، f/1.6، OIS",
    camera_ultrawide: "لا",
    camera_front: "12 ميجابكسل، f/1.9",
    camera_video: "4K@60fps، Dolby Vision",
    audio_speakers: "ستيريو",
    audio_jack: "لا",
    connectivity_sim: "نانو سيم + eSIM",
    connectivity_network: "5G SA/NSA",
    connectivity_wifi: "Wi-Fi 6E",
    connectivity_bluetooth: "5.3",
    connectivity_nfc: "نعم",
    connectivity_gps: "GPS، GLONASS، Galileo، BeiDou",
    protection_water: "IP68",
    protection_standard: "IP68",
    battery_capacity: "3500 مللي أمبير",
    battery_charging: "30 واط",
    battery_wireless: "15 واط MagSafe",
    battery_reverse: "لا",
    software_os: "iOS 26",
    software_ui: "iOS 26",
    sensor_fingerprint: "لا",
    sensor_face_unlock: "Face ID",
    sensor_gyroscope: "نعم",
    sensor_compass: "نعم",
    sensor_proximity: "نعم",
    sensor_light: "نعم",
    sensor_other: "مقياس التسارع، البارومتر"
  },

  // ==================== GOOGLE 2025 ====================

  // Google Pixel 10 Pro
  {
    slug: "google-pixel-10-pro",
    name: "Google Pixel 10 Pro",
    name_ar: "جوجل بيكسل 10 برو",
    brand: "Google",
    year: 2025,
    release_date: "أغسطس 2025",
    image: "https://fdn2.gsmarena.com/vv/bigpic/google-pixel-10-pro.jpg",
    status: "published",
    quick_screen: "6.3 بوصة LTPO OLED، 120Hz",
    quick_processor: "Google Tensor G5",
    quick_camera: "50 ميجابكسل رئيسية",
    quick_front_camera: "42 ميجابكسل",
    quick_memory: "128/256/512GB/1TB مع 16GB رام",
    quick_battery: "4870 مللي أمبير، شحن 30 واط",
    design_height: "152.8 ملم",
    design_width: "72.0 ملم",
    design_thickness: "8.5 ملم",
    design_weight: "207 جرام",
    design_materials: "زجاج Gorilla Glass Victus 2، إطار ألمنيوم",
    design_colors: "Moonstone، Jade، Porcelain، Obsidian",
    design_frame: "إطار ألمنيوم",
    screen_type: "LTPO OLED",
    screen_size: "6.3 بوصة",
    screen_resolution: "1280 × 2856 بكسل",
    screen_ppi: "495 بكسل لكل بوصة",
    screen_refresh_rate: "1-120Hz",
    screen_brightness: "3300 نيت (ذروة)",
    screen_protection: "Corning Gorilla Glass Victus 2",
    processor_name: "Google Tensor G5 (3nm)",
    processor_cores: "ثماني النواة",
    processor_frequency: "1×3.78 GHz Cortex-X4 + 5×3.05 GHz Cortex-A725 + 2×2.25 GHz Cortex-A520",
    processor_gpu: "PowerVR DXT-48-1536",
    processor_fabrication: "3 نانومتر",
    antutu_score: "1,470,000",
    memory_storage: "128/256/512GB/1TB",
    memory_ram: "16GB",
    memory_type: "UFS 4.0 (UFS 3.1 لـ 128GB)",
    memory_sd_card: "لا",
    camera_main: "50 ميجابكسل، f/1.7، 25mm، OIS، Dual Pixel PDAF",
    camera_ultrawide: "48 ميجابكسل، f/1.7، 123°، Dual Pixel PDAF",
    camera_telephoto: "48 ميجابكسل، f/2.8، 113mm بيريسكوب، تقريب بصري 5×، OIS",
    camera_front: "42 ميجابكسل، f/2.2، 17mm، PDAF",
    camera_video: "8K@30fps (via cloud)، 4K@60fps، 10-bit HDR",
    audio_speakers: "ستيريو",
    audio_jack: "لا",
    connectivity_sim: "Nano-SIM + eSIM (حتى 8 eSIMs)",
    connectivity_network: "5G SA/NSA",
    connectivity_wifi: "Wi-Fi 7 (802.11be) ثلاثي النطاق",
    connectivity_bluetooth: "6.0، aptX HD",
    connectivity_nfc: "نعم",
    connectivity_gps: "GPS (L1+L5)، GLONASS، Galileo، BeiDou، QZSS، NavIC",
    protection_water: "IP68",
    protection_standard: "IP68 (حتى 1.5 متر لمدة 30 دقيقة)",
    battery_capacity: "4870 مللي أمبير",
    battery_charging: "30 واط سلكي (55% في 30 دقيقة)",
    battery_wireless: "15 واط Qi2 مغناطيسي",
    battery_reverse: "شحن عكسي سلكي، Bypass charging",
    software_os: "Android 16",
    software_ui: "Pixel UI",
    sensor_fingerprint: "بالموجات فوق الصوتية تحت الشاشة",
    sensor_face_unlock: "نعم",
    sensor_gyroscope: "نعم",
    sensor_compass: "نعم",
    sensor_proximity: "نعم",
    sensor_light: "نعم",
    sensor_other: "مقياس التسارع، البارومتر، مقياس حرارة الجلد، UWB، Satellite SOS"
  },

  // Google Pixel 10 Pro XL
  {
    slug: "google-pixel-10-pro-xl",
    name: "Google Pixel 10 Pro XL",
    name_ar: "جوجل بيكسل 10 برو XL",
    brand: "Google",
    year: 2025,
    release_date: "أغسطس 2025",
    image: "https://fdn2.gsmarena.com/vv/bigpic/google-pixel-10-pro-xl.jpg",
    status: "published",
    quick_screen: "6.7 بوصة LTPO OLED، 120Hz",
    quick_processor: "Google Tensor G5",
    quick_camera: "50 ميجابكسل رئيسية",
    quick_front_camera: "42 ميجابكسل",
    quick_memory: "128/256/512GB/1TB مع 16GB رام",
    quick_battery: "5200 مللي أمبير، شحن 45 واط",
    design_height: "162.0 ملم",
    design_width: "76.5 ملم",
    design_thickness: "8.7 ملم",
    design_weight: "225 جرام",
    design_materials: "زجاج Gorilla Glass Victus 2، إطار ألمنيوم",
    design_colors: "Moonstone، Jade، Porcelain، Obsidian",
    design_frame: "إطار ألمنيوم",
    screen_type: "LTPO OLED",
    screen_size: "6.7 بوصة",
    screen_resolution: "1344 × 2992 بكسل",
    screen_ppi: "486 بكسل لكل بوصة",
    screen_refresh_rate: "1-120Hz",
    screen_brightness: "3300 نيت",
    screen_protection: "Corning Gorilla Glass Victus 2",
    processor_name: "Google Tensor G5 (3nm)",
    processor_cores: "ثماني النواة",
    processor_frequency: "1×3.78 GHz + 5×3.05 GHz + 2×2.25 GHz",
    processor_gpu: "PowerVR DXT-48-1536",
    processor_fabrication: "3 نانومتر",
    antutu_score: "1,470,000",
    memory_storage: "128/256/512GB/1TB",
    memory_ram: "16GB",
    memory_type: "UFS 4.0",
    memory_sd_card: "لا",
    camera_main: "50 ميجابكسل، f/1.7، OIS",
    camera_ultrawide: "48 ميجابكسل، f/1.7، 123°",
    camera_telephoto: "48 ميجابكسل، f/2.8، تقريب بصري 5× بيريسكوب",
    camera_front: "42 ميجابكسل، f/2.2",
    camera_video: "8K@30fps، 4K@60fps، 10-bit HDR",
    audio_speakers: "ستيريو",
    audio_jack: "لا",
    connectivity_sim: "Nano-SIM + eSIM",
    connectivity_network: "5G SA/NSA",
    connectivity_wifi: "Wi-Fi 7",
    connectivity_bluetooth: "6.0",
    connectivity_nfc: "نعم",
    connectivity_gps: "GPS، GLONASS، Galileo، BeiDou، QZSS، NavIC",
    protection_water: "IP68",
    protection_standard: "IP68",
    battery_capacity: "5200 مللي أمبير",
    battery_charging: "45 واط",
    battery_wireless: "23 واط",
    battery_reverse: "شحن عكسي",
    software_os: "Android 16",
    software_ui: "Pixel UI",
    sensor_fingerprint: "بالموجات فوق الصوتية تحت الشاشة",
    sensor_face_unlock: "نعم",
    sensor_gyroscope: "نعم",
    sensor_compass: "نعم",
    sensor_proximity: "نعم",
    sensor_light: "نعم",
    sensor_other: "مقياس التسارع، البارومتر، مقياس الحرارة، UWB"
  },

  // Google Pixel 10
  {
    slug: "google-pixel-10",
    name: "Google Pixel 10",
    name_ar: "جوجل بيكسل 10",
    brand: "Google",
    year: 2025,
    release_date: "أغسطس 2025",
    image: "https://fdn2.gsmarena.com/vv/bigpic/google-pixel-10.jpg",
    status: "published",
    quick_screen: "6.3 بوصة OLED، 120Hz",
    quick_processor: "Google Tensor G5",
    quick_camera: "50 ميجابكسل رئيسية",
    quick_front_camera: "13 ميجابكسل",
    quick_memory: "128/256GB مع 12GB رام",
    quick_battery: "4500 مللي أمبير، شحن 27 واط",
    design_height: "152.5 ملم",
    design_width: "72.0 ملم",
    design_thickness: "8.3 ملم",
    design_weight: "185 جرام",
    design_materials: "زجاج Gorilla Glass Victus 2، إطار ألمنيوم",
    design_colors: "Obsidian، Porcelain، Rose",
    design_frame: "إطار ألمنيوم معاد تدويره",
    screen_type: "OLED",
    screen_size: "6.3 بوصة",
    screen_resolution: "1080 × 2400 بكسل",
    screen_ppi: "418 بكسل لكل بوصة",
    screen_refresh_rate: "90Hz",
    screen_brightness: "2000 نيت",
    screen_protection: "Corning Gorilla Glass Victus 2",
    processor_name: "Google Tensor G5 (3nm)",
    processor_cores: "ثماني النواة",
    processor_frequency: "1×3.78 GHz + 5×3.05 GHz + 2×2.25 GHz",
    processor_gpu: "PowerVR DXT-48-1536",
    processor_fabrication: "3 نانومتر",
    antutu_score: "1,400,000",
    memory_storage: "128/256GB",
    memory_ram: "12GB",
    memory_type: "UFS 3.1",
    memory_sd_card: "لا",
    camera_main: "50 ميجابكسل، f/1.8، OIS، PDAF",
    camera_ultrawide: "12 ميجابكسل، f/2.2، 120°",
    camera_front: "13 ميجابكسل، f/2.2",
    camera_video: "4K@60fps، 10-bit HDR",
    audio_speakers: "ستيريو",
    audio_jack: "لا",
    connectivity_sim: "Nano-SIM + eSIM",
    connectivity_network: "5G SA/NSA",
    connectivity_wifi: "Wi-Fi 6E",
    connectivity_bluetooth: "5.3",
    connectivity_nfc: "نعم",
    connectivity_gps: "GPS، GLONASS، Galileo، BeiDou",
    protection_water: "IP68",
    protection_standard: "IP68",
    battery_capacity: "4500 مللي أمبير",
    battery_charging: "27 واط",
    battery_wireless: "12 واط",
    battery_reverse: "شحن عكسي",
    software_os: "Android 16",
    software_ui: "Pixel UI",
    sensor_fingerprint: "بصري تحت الشاشة",
    sensor_face_unlock: "نعم",
    sensor_gyroscope: "نعم",
    sensor_compass: "نعم",
    sensor_proximity: "نعم",
    sensor_light: "نعم",
    sensor_other: "مقياس التسارع، البارومتر"
  },

  // Google Pixel 10a
  {
    slug: "google-pixel-10a",
    name: "Google Pixel 10a",
    name_ar: "جوجل بيكسل 10a",
    brand: "Google",
    year: 2025,
    release_date: "مايو 2025",
    image: "https://fdn2.gsmarena.com/vv/bigpic/google-pixel-10a.jpg",
    status: "published",
    quick_screen: "6.1 بوصة OLED، 90Hz",
    quick_processor: "Google Tensor G4",
    quick_camera: "64 ميجابكسل رئيسية",
    quick_front_camera: "13 ميجابكسل",
    quick_memory: "128/256GB مع 8GB رام",
    quick_battery: "5000 مللي أمبير، شحن 23 واط",
    design_height: "153.5 ملم",
    design_width: "72.8 ملم",
    design_thickness: "8.6 ملم",
    design_weight: "186 جرام",
    design_materials: "زجاج Gorilla Glass 3، إطار بلاستيك",
    design_colors: "أسود، أبيض، أخضر",
    design_frame: "إطار بلاستيك",
    screen_type: "OLED",
    screen_size: "6.1 بوصة",
    screen_resolution: "1080 × 2400 بكسل",
    screen_ppi: "431 بكسل لكل بوصة",
    screen_refresh_rate: "90Hz",
    screen_brightness: "1400 نيت",
    screen_protection: "Corning Gorilla Glass 3",
    processor_name: "Google Tensor G4 (4nm)",
    processor_cores: "ثماني النواة",
    processor_frequency: "1×3.1 GHz + 4×2.6 GHz + 3×1.9 GHz",
    processor_gpu: "Mali-G715 MC7",
    processor_fabrication: "4 نانومتر",
    antutu_score: "1,100,000",
    memory_storage: "128/256GB",
    memory_ram: "8GB",
    memory_type: "UFS 3.1",
    memory_sd_card: "لا",
    camera_main: "64 ميجابكسل، f/1.9، OIS، PDAF",
    camera_ultrawide: "13 ميجابكسل، f/2.2، 120°",
    camera_front: "13 ميجابكسل، f/2.2",
    camera_video: "4K@60fps",
    audio_speakers: "ستيريو",
    audio_jack: "لا",
    connectivity_sim: "Nano-SIM + eSIM",
    connectivity_network: "5G SA/NSA",
    connectivity_wifi: "Wi-Fi 6E",
    connectivity_bluetooth: "5.3",
    connectivity_nfc: "نعم",
    connectivity_gps: "GPS، GLONASS، Galileo، BeiDou",
    protection_water: "IP67",
    protection_standard: "IP67",
    battery_capacity: "5000 مللي أمبير",
    battery_charging: "23 واط",
    battery_wireless: "7.5 واط",
    battery_reverse: "لا",
    software_os: "Android 15",
    software_ui: "Pixel UI",
    sensor_fingerprint: "بصري تحت الشاشة",
    sensor_face_unlock: "نعم",
    sensor_gyroscope: "نعم",
    sensor_compass: "نعم",
    sensor_proximity: "نعم",
    sensor_light: "نعم",
    sensor_other: "مقياس التسارع"
  },

  // ==================== XIAOMI 2025 ====================

  // Xiaomi 15 Ultra
  {
    slug: "xiaomi-15-ultra",
    name: "Xiaomi 15 Ultra",
    name_ar: "شاومي 15 ألترا",
    brand: "Xiaomi",
    year: 2025,
    release_date: "فبراير 2025",
    image: "https://fdn2.gsmarena.com/vv/bigpic/xiaomi-15-ultra.jpg",
    status: "published",
    quick_screen: "6.73 بوصة LTPO AMOLED، 120Hz",
    quick_processor: "Snapdragon 8 Elite",
    quick_camera: "50 ميجابكسل Leica عدسة متغيرة",
    quick_front_camera: "32 ميجابكسل",
    quick_memory: "256/512GB/1TB مع 16GB رام",
    quick_battery: "5000 مللي أمبير، شحن 90 واط",
    design_height: "161.3 ملم",
    design_width: "75.1 ملم",
    design_thickness: "9.2 ملم",
    design_weight: "229 جرام",
    design_materials: "زجاج Ceramic، إطار ألمنيوم",
    design_colors: "أسود، أبيض، أخضر",
    design_frame: "إطار ألمنيوم",
    screen_type: "LTPO AMOLED",
    screen_size: "6.73 بوصة",
    screen_resolution: "1440 × 3200 بكسل",
    screen_ppi: "522 بكسل لكل بوصة",
    screen_refresh_rate: "1-120Hz",
    screen_brightness: "3200 نيت (ذروة)",
    screen_protection: "Ceramic Glass",
    processor_name: "Qualcomm Snapdragon 8 Elite (3nm)",
    processor_cores: "ثماني النواة",
    processor_frequency: "2×4.32 GHz + 6×3.53 GHz",
    processor_gpu: "Adreno 830",
    processor_fabrication: "3 نانومتر",
    antutu_score: "2,900,000",
    memory_storage: "256/512GB/1TB",
    memory_ram: "16GB",
    memory_type: "UFS 4.0",
    memory_sd_card: "لا",
    camera_main: "50 ميجابكسل Leica Summilux، f/1.63-4.0 عدسة متغيرة، OIS",
    camera_ultrawide: "50 ميجابكسل، f/1.8، 122°",
    camera_telephoto: "50 ميجابكسل بيريسكوب، f/2.5، تقريب بصري 5× + 200 ميجابكسل تليفوتو",
    camera_front: "32 ميجابكسل، f/2.0",
    camera_video: "8K@30fps، 4K@120fps، Dolby Vision",
    audio_speakers: "ستيريو، Harman Kardon",
    audio_jack: "لا",
    connectivity_sim: "Nano-SIM + eSIM",
    connectivity_network: "5G SA/NSA",
    connectivity_wifi: "Wi-Fi 7",
    connectivity_bluetooth: "5.4",
    connectivity_nfc: "نعم",
    connectivity_gps: "GPS، GLONASS، Galileo، BeiDou، NavIC",
    protection_water: "IP68",
    protection_standard: "IP68",
    battery_capacity: "5000 مللي أمبير",
    battery_charging: "90 واط سلكي (100% في 35 دقيقة)",
    battery_wireless: "80 واط",
    battery_reverse: "10 واط",
    software_os: "Android 15",
    software_ui: "HyperOS 2.0",
    sensor_fingerprint: "بالموجات فوق الصوتية تحت الشاشة",
    sensor_face_unlock: "نعم",
    sensor_gyroscope: "نعم",
    sensor_compass: "نعم",
    sensor_proximity: "نعم",
    sensor_light: "نعم",
    sensor_other: "مقياس التسارع، البارومتر، الأشعة تحت الحمراء"
  },

  // Xiaomi 15 Pro
  {
    slug: "xiaomi-15-pro",
    name: "Xiaomi 15 Pro",
    name_ar: "شاومي 15 برو",
    brand: "Xiaomi",
    year: 2025,
    release_date: "أكتوبر 2024",
    image: "https://fdn2.gsmarena.com/vv/bigpic/xiaomi-15-pro.jpg",
    status: "published",
    quick_screen: "6.73 بوصة LTPO AMOLED، 120Hz",
    quick_processor: "Snapdragon 8 Elite",
    quick_camera: "50 ميجابكسل Leica",
    quick_front_camera: "32 ميجابكسل",
    quick_memory: "256/512GB مع 12/16GB رام",
    quick_battery: "6100 مللي أمبير، شحن 90 واط",
    design_height: "161.2 ملم",
    design_width: "74.8 ملم",
    design_thickness: "8.5 ملم",
    design_weight: "213 جرام",
    design_materials: "زجاج Gorilla Glass Victus 2، إطار ألمنيوم",
    design_colors: "أسود، أبيض، أخضر، رمادي",
    design_frame: "إطار ألمنيوم",
    screen_type: "LTPO AMOLED",
    screen_size: "6.73 بوصة",
    screen_resolution: "1440 × 3200 بكسل",
    screen_ppi: "522 بكسل لكل بوصة",
    screen_refresh_rate: "1-120Hz",
    screen_brightness: "3200 نيت",
    screen_protection: "Corning Gorilla Glass Victus 2",
    processor_name: "Qualcomm Snapdragon 8 Elite (3nm)",
    processor_cores: "ثماني النواة",
    processor_frequency: "2×4.32 GHz + 6×3.53 GHz",
    processor_gpu: "Adreno 830",
    processor_fabrication: "3 نانومتر",
    antutu_score: "2,800,000",
    memory_storage: "256/512GB",
    memory_ram: "12/16GB",
    memory_type: "UFS 4.0",
    memory_sd_card: "لا",
    camera_main: "50 ميجابكسل Leica، f/1.44، OIS",
    camera_ultrawide: "50 ميجابكسل، f/2.2، 115°",
    camera_telephoto: "50 ميجابكسل، f/2.5، تقريب بصري 3×",
    camera_front: "32 ميجابكسل، f/2.0",
    camera_video: "8K@30fps، 4K@60fps",
    audio_speakers: "ستيريو",
    audio_jack: "لا",
    connectivity_sim: "Nano-SIM + eSIM",
    connectivity_network: "5G SA/NSA",
    connectivity_wifi: "Wi-Fi 7",
    connectivity_bluetooth: "5.4",
    connectivity_nfc: "نعم",
    connectivity_gps: "GPS، GLONASS، Galileo، BeiDou",
    protection_water: "IP68",
    protection_standard: "IP68",
    battery_capacity: "6100 مللي أمبير",
    battery_charging: "90 واط",
    battery_wireless: "50 واط",
    battery_reverse: "10 واط",
    software_os: "Android 15",
    software_ui: "HyperOS 2.0",
    sensor_fingerprint: "بالموجات فوق الصوتية تحت الشاشة",
    sensor_face_unlock: "نعم",
    sensor_gyroscope: "نعم",
    sensor_compass: "نعم",
    sensor_proximity: "نعم",
    sensor_light: "نعم",
    sensor_other: "مقياس التسارع، الأشعة تحت الحمراء"
  },

  // Xiaomi 15
  {
    slug: "xiaomi-15",
    name: "Xiaomi 15",
    name_ar: "شاومي 15",
    brand: "Xiaomi",
    year: 2025,
    release_date: "أكتوبر 2024",
    image: "https://fdn2.gsmarena.com/vv/bigpic/xiaomi-15.jpg",
    status: "published",
    quick_screen: "6.36 بوصة LTPO AMOLED، 120Hz",
    quick_processor: "Snapdragon 8 Elite",
    quick_camera: "50 ميجابكسل Leica",
    quick_front_camera: "32 ميجابكسل",
    quick_memory: "256/512GB مع 12/16GB رام",
    quick_battery: "5400 مللي أمبير، شحن 90 واط",
    design_height: "152.3 ملم",
    design_width: "71.2 ملم",
    design_thickness: "8.1 ملم",
    design_weight: "191 جرام",
    design_materials: "زجاج Gorilla Glass Victus 2، إطار ألمنيوم",
    design_colors: "أسود، أبيض، أخضر، بنفسجي",
    design_frame: "إطار ألمنيوم",
    screen_type: "LTPO AMOLED",
    screen_size: "6.36 بوصة",
    screen_resolution: "1200 × 2670 بكسل",
    screen_ppi: "460 بكسل لكل بوصة",
    screen_refresh_rate: "1-120Hz",
    screen_brightness: "3200 نيت",
    screen_protection: "Corning Gorilla Glass Victus 2",
    processor_name: "Qualcomm Snapdragon 8 Elite (3nm)",
    processor_cores: "ثماني النواة",
    processor_frequency: "2×4.32 GHz + 6×3.53 GHz",
    processor_gpu: "Adreno 830",
    processor_fabrication: "3 نانومتر",
    antutu_score: "2,800,000",
    memory_storage: "256/512GB",
    memory_ram: "12/16GB",
    memory_type: "UFS 4.0",
    memory_sd_card: "لا",
    camera_main: "50 ميجابكسل Leica، f/1.6، OIS",
    camera_ultrawide: "50 ميجابكسل، f/2.2، 115°",
    camera_telephoto: "50 ميجابكسل، f/2.0، تقريب بصري 3×",
    camera_front: "32 ميجابكسل، f/2.0",
    camera_video: "8K@30fps، 4K@60fps",
    audio_speakers: "ستيريو",
    audio_jack: "لا",
    connectivity_sim: "Nano-SIM + eSIM",
    connectivity_network: "5G SA/NSA",
    connectivity_wifi: "Wi-Fi 7",
    connectivity_bluetooth: "5.4",
    connectivity_nfc: "نعم",
    connectivity_gps: "GPS، GLONASS، Galileo، BeiDou",
    protection_water: "IP68",
    protection_standard: "IP68",
    battery_capacity: "5400 مللي أمبير",
    battery_charging: "90 واط",
    battery_wireless: "50 واط",
    battery_reverse: "10 واط",
    software_os: "Android 15",
    software_ui: "HyperOS 2.0",
    sensor_fingerprint: "بصري تحت الشاشة",
    sensor_face_unlock: "نعم",
    sensor_gyroscope: "نعم",
    sensor_compass: "نعم",
    sensor_proximity: "نعم",
    sensor_light: "نعم",
    sensor_other: "مقياس التسارع، الأشعة تحت الحمراء"
  },

  // POCO F7 Pro
  {
    slug: "poco-f7-pro",
    name: "POCO F7 Pro",
    name_ar: "بوكو F7 برو",
    brand: "Xiaomi",
    year: 2025,
    release_date: "مارس 2025",
    image: "https://fdn2.gsmarena.com/vv/bigpic/xiaomi-poco-f7-pro.jpg",
    status: "published",
    quick_screen: "6.67 بوصة AMOLED، 120Hz",
    quick_processor: "Snapdragon 8 Gen 3",
    quick_camera: "50 ميجابكسل رئيسية",
    quick_front_camera: "20 ميجابكسل",
    quick_memory: "256/512GB مع 12GB رام",
    quick_battery: "6000 مللي أمبير، شحن 90 واط",
    design_height: "160.3 ملم",
    design_width: "75.0 ملم",
    design_thickness: "8.1 ملم",
    design_weight: "206 جرام",
    design_materials: "زجاج Gorilla Glass 7i، إطار ألمنيوم",
    design_colors: "أسود، أزرق، فضي",
    design_frame: "إطار ألمنيوم",
    screen_type: "AMOLED",
    screen_size: "6.67 بوصة",
    screen_resolution: "1440 × 3200 بكسل",
    screen_ppi: "526 بكسل لكل بوصة",
    screen_refresh_rate: "120Hz",
    screen_brightness: "3200 نيت (ذروة)",
    screen_protection: "Corning Gorilla Glass 7i",
    processor_name: "Qualcomm Snapdragon 8 Gen 3 (4nm)",
    processor_cores: "ثماني النواة",
    processor_frequency: "1×3.3 GHz + 3×3.2 GHz + 2×3.0 GHz + 2×2.3 GHz",
    processor_gpu: "Adreno 750",
    processor_fabrication: "4 نانومتر",
    antutu_score: "2,065,000",
    memory_storage: "256/512GB",
    memory_ram: "12GB",
    memory_type: "UFS 4.1",
    memory_sd_card: "لا",
    camera_main: "50 ميجابكسل، f/1.6، OIS، Dual Pixel PDAF",
    camera_ultrawide: "8 ميجابكسل، f/2.2",
    camera_front: "20 ميجابكسل",
    camera_video: "8K@24fps، 4K@60fps، 1080p@960fps slow-mo",
    audio_speakers: "ستيريو، Hi-Res، Snapdragon Sound",
    audio_jack: "لا",
    connectivity_sim: "Nano-SIM + Nano-SIM",
    connectivity_network: "5G SA/NSA",
    connectivity_wifi: "Wi-Fi 7",
    connectivity_bluetooth: "5.4",
    connectivity_nfc: "نعم",
    connectivity_gps: "GPS (L1+L5)، GLONASS، Galileo، BeiDou، QZSS، NavIC",
    protection_water: "IP68",
    protection_standard: "IP68 (حتى 2.5 متر لمدة 30 دقيقة)",
    battery_capacity: "6000 مللي أمبير",
    battery_charging: "90 واط (100% في 37 دقيقة)",
    battery_wireless: "لا",
    battery_reverse: "لا",
    software_os: "Android 15",
    software_ui: "HyperOS 2",
    sensor_fingerprint: "بالموجات فوق الصوتية تحت الشاشة",
    sensor_face_unlock: "نعم",
    sensor_gyroscope: "نعم",
    sensor_compass: "نعم",
    sensor_proximity: "نعم",
    sensor_light: "نعم",
    sensor_other: "مقياس التسارع، الأشعة تحت الحمراء"
  },

  // POCO F7
  {
    slug: "poco-f7",
    name: "POCO F7",
    name_ar: "بوكو F7",
    brand: "Xiaomi",
    year: 2025,
    release_date: "مارس 2025",
    image: "https://fdn2.gsmarena.com/vv/bigpic/xiaomi-poco-f7.jpg",
    status: "published",
    quick_screen: "6.67 بوصة AMOLED، 120Hz",
    quick_processor: "Snapdragon 8s Gen 3",
    quick_camera: "50 ميجابكسل رئيسية",
    quick_front_camera: "20 ميجابكسل",
    quick_memory: "256/512GB مع 8/12GB رام",
    quick_battery: "5500 مللي أمبير، شحن 67 واط",
    design_height: "160.5 ملم",
    design_width: "75.2 ملم",
    design_thickness: "8.0 ملم",
    design_weight: "195 جرام",
    design_materials: "زجاج Gorilla Glass 7، إطار بلاستيك",
    design_colors: "أسود، أزرق، أخضر",
    design_frame: "إطار بلاستيك",
    screen_type: "AMOLED",
    screen_size: "6.67 بوصة",
    screen_resolution: "1220 × 2712 بكسل",
    screen_ppi: "446 بكسل لكل بوصة",
    screen_refresh_rate: "120Hz",
    screen_brightness: "2400 نيت",
    screen_protection: "Corning Gorilla Glass 7",
    processor_name: "Qualcomm Snapdragon 8s Gen 3 (4nm)",
    processor_cores: "ثماني النواة",
    processor_frequency: "1×3.0 GHz + 4×2.8 GHz + 3×2.0 GHz",
    processor_gpu: "Adreno 735",
    processor_fabrication: "4 نانومتر",
    antutu_score: "1,600,000",
    memory_storage: "256/512GB",
    memory_ram: "8/12GB",
    memory_type: "UFS 4.0",
    memory_sd_card: "لا",
    camera_main: "50 ميجابكسل، f/1.7، OIS، PDAF",
    camera_ultrawide: "8 ميجابكسل، f/2.2، 120°",
    camera_front: "20 ميجابكسل، f/2.0",
    camera_video: "4K@60fps، 1080p@240fps",
    audio_speakers: "ستيريو",
    audio_jack: "لا",
    connectivity_sim: "Nano-SIM + Nano-SIM",
    connectivity_network: "5G SA/NSA",
    connectivity_wifi: "Wi-Fi 6E",
    connectivity_bluetooth: "5.3",
    connectivity_nfc: "نعم",
    connectivity_gps: "GPS، GLONASS، Galileo، BeiDou",
    protection_water: "IP54",
    protection_standard: "IP54",
    battery_capacity: "5500 مللي أمبير",
    battery_charging: "67 واط",
    battery_wireless: "لا",
    battery_reverse: "لا",
    software_os: "Android 15",
    software_ui: "HyperOS 2",
    sensor_fingerprint: "بصري تحت الشاشة",
    sensor_face_unlock: "نعم",
    sensor_gyroscope: "نعم",
    sensor_compass: "نعم",
    sensor_proximity: "نعم",
    sensor_light: "نعم",
    sensor_other: "مقياس التسارع، الأشعة تحت الحمراء"
  },

  // Redmi Note 14 Pro+
  {
    slug: "redmi-note-14-pro-plus",
    name: "Redmi Note 14 Pro+",
    name_ar: "ريدمي نوت 14 برو بلس",
    brand: "Xiaomi",
    year: 2025,
    release_date: "يناير 2025",
    image: "https://fdn2.gsmarena.com/vv/bigpic/xiaomi-redmi-note-14-pro-plus-global.jpg",
    status: "published",
    quick_screen: "6.67 بوصة AMOLED، 120Hz",
    quick_processor: "Snapdragon 7s Gen 3",
    quick_camera: "200 ميجابكسل رئيسية",
    quick_front_camera: "20 ميجابكسل",
    quick_memory: "128/256/512GB مع 8/12GB رام",
    quick_battery: "5110 مللي أمبير، شحن 120 واط",
    design_height: "162.5 ملم",
    design_width: "74.7 ملم",
    design_thickness: "8.2 ملم",
    design_weight: "195 جرام",
    design_materials: "زجاج Gorilla Glass Victus 2، إطار ألمنيوم",
    design_colors: "أسود، أزرق، بنفسجي، أبيض",
    design_frame: "إطار ألمنيوم",
    screen_type: "AMOLED",
    screen_size: "6.67 بوصة",
    screen_resolution: "1220 × 2712 بكسل",
    screen_ppi: "446 بكسل لكل بوصة",
    screen_refresh_rate: "120Hz",
    screen_brightness: "2400 نيت",
    screen_protection: "Corning Gorilla Glass Victus 2",
    processor_name: "Qualcomm Snapdragon 7s Gen 3 (4nm)",
    processor_cores: "ثماني النواة",
    processor_frequency: "2×2.5 GHz + 6×2.0 GHz",
    processor_gpu: "Adreno 710",
    processor_fabrication: "4 نانومتر",
    antutu_score: "780,000",
    memory_storage: "128/256/512GB",
    memory_ram: "8/12GB",
    memory_type: "UFS 2.2",
    memory_sd_card: "نعم، حتى 1TB",
    camera_main: "200 ميجابكسل، f/1.65، OIS، PDAF",
    camera_ultrawide: "8 ميجابكسل، f/2.2، 120°",
    camera_telephoto: "2 ميجابكسل، f/2.4، ماكرو",
    camera_front: "20 ميجابكسل، f/2.2",
    camera_video: "4K@30fps، 1080p@60fps",
    audio_speakers: "ستيريو",
    audio_jack: "لا",
    connectivity_sim: "Nano-SIM + Nano-SIM أو eSIM",
    connectivity_network: "5G SA/NSA",
    connectivity_wifi: "Wi-Fi 6",
    connectivity_bluetooth: "5.3",
    connectivity_nfc: "نعم",
    connectivity_gps: "GPS، GLONASS، Galileo، BeiDou",
    protection_water: "IP68",
    protection_standard: "IP68",
    battery_capacity: "5110 مللي أمبير",
    battery_charging: "120 واط (50% في 9 دقائق)",
    battery_wireless: "لا",
    battery_reverse: "لا",
    software_os: "Android 14",
    software_ui: "HyperOS",
    sensor_fingerprint: "بصري تحت الشاشة",
    sensor_face_unlock: "نعم",
    sensor_gyroscope: "نعم",
    sensor_compass: "نعم",
    sensor_proximity: "نعم",
    sensor_light: "نعم",
    sensor_other: "مقياس التسارع، الأشعة تحت الحمراء"
  },

  // ==================== ONEPLUS 2025 ====================

  // OnePlus 13
  {
    slug: "oneplus-13",
    name: "OnePlus 13",
    name_ar: "ون بلس 13",
    brand: "OnePlus",
    year: 2025,
    release_date: "يناير 2025",
    image: "https://fdn2.gsmarena.com/vv/bigpic/oneplus-13.jpg",
    status: "published",
    quick_screen: "6.82 بوصة LTPO AMOLED، 120Hz",
    quick_processor: "Snapdragon 8 Elite",
    quick_camera: "50 ميجابكسل Hasselblad",
    quick_front_camera: "32 ميجابكسل",
    quick_memory: "256/512GB مع 12/16GB رام",
    quick_battery: "6000 مللي أمبير، شحن 100 واط",
    design_height: "162.9 ملم",
    design_width: "76.5 ملم",
    design_thickness: "8.5 ملم",
    design_weight: "213 جرام",
    design_materials: "زجاج Gorilla Glass Victus 2، إطار ألمنيوم",
    design_colors: "أسود ميدنايت، أزرق بحري، أبيض قطبي",
    design_frame: "إطار ألمنيوم",
    screen_type: "LTPO AMOLED",
    screen_size: "6.82 بوصة",
    screen_resolution: "1440 × 3168 بكسل",
    screen_ppi: "510 بكسل لكل بوصة",
    screen_refresh_rate: "1-120Hz",
    screen_brightness: "4500 نيت (ذروة)",
    screen_protection: "Corning Gorilla Glass Victus 2",
    processor_name: "Qualcomm Snapdragon 8 Elite (3nm)",
    processor_cores: "ثماني النواة",
    processor_frequency: "2×4.32 GHz + 6×3.53 GHz",
    processor_gpu: "Adreno 830",
    processor_fabrication: "3 نانومتر",
    antutu_score: "2,900,000",
    memory_storage: "256/512GB",
    memory_ram: "12/16GB",
    memory_type: "UFS 4.0",
    memory_sd_card: "لا",
    camera_main: "50 ميجابكسل Hasselblad، f/1.6، OIS، PDAF",
    camera_ultrawide: "50 ميجابكسل، f/2.0، 120°",
    camera_telephoto: "50 ميجابكسل، f/2.6، تقريب بصري 3×",
    camera_front: "32 ميجابكسل، f/2.4",
    camera_video: "8K@24fps، 4K@120fps، Dolby Vision",
    audio_speakers: "ستيريو",
    audio_jack: "لا",
    connectivity_sim: "Nano-SIM + eSIM",
    connectivity_network: "5G SA/NSA",
    connectivity_wifi: "Wi-Fi 7",
    connectivity_bluetooth: "5.4",
    connectivity_nfc: "نعم",
    connectivity_gps: "GPS، GLONASS، Galileo، BeiDou، NavIC",
    protection_water: "IP69",
    protection_standard: "IP68/IP69",
    battery_capacity: "6000 مللي أمبير",
    battery_charging: "100 واط سلكي",
    battery_wireless: "50 واط",
    battery_reverse: "10 واط",
    software_os: "Android 15",
    software_ui: "OxygenOS 15",
    sensor_fingerprint: "بالموجات فوق الصوتية تحت الشاشة",
    sensor_face_unlock: "نعم",
    sensor_gyroscope: "نعم",
    sensor_compass: "نعم",
    sensor_proximity: "نعم",
    sensor_light: "نعم",
    sensor_other: "مقياس التسارع، الأشعة تحت الحمراء"
  },

  // OnePlus 13R
  {
    slug: "oneplus-13r",
    name: "OnePlus 13R",
    name_ar: "ون بلس 13R",
    brand: "OnePlus",
    year: 2025,
    release_date: "يناير 2025",
    image: "https://fdn2.gsmarena.com/vv/bigpic/oneplus-13r.jpg",
    status: "published",
    quick_screen: "6.78 بوصة AMOLED، 120Hz",
    quick_processor: "Snapdragon 8 Gen 3",
    quick_camera: "50 ميجابكسل رئيسية",
    quick_front_camera: "16 ميجابكسل",
    quick_memory: "256/512GB مع 12/16GB رام",
    quick_battery: "6000 مللي أمبير، شحن 80 واط",
    design_height: "161.7 ملم",
    design_width: "75.8 ملم",
    design_thickness: "8.0 ملم",
    design_weight: "206 جرام",
    design_materials: "زجاج Gorilla Glass 7i، إطار ألمنيوم",
    design_colors: "أسود، أزرق",
    design_frame: "إطار ألمنيوم",
    screen_type: "AMOLED",
    screen_size: "6.78 بوصة",
    screen_resolution: "1264 × 2780 بكسل",
    screen_ppi: "450 بكسل لكل بوصة",
    screen_refresh_rate: "120Hz",
    screen_brightness: "4500 نيت",
    screen_protection: "Corning Gorilla Glass 7i",
    processor_name: "Qualcomm Snapdragon 8 Gen 3 (4nm)",
    processor_cores: "ثماني النواة",
    processor_frequency: "1×3.3 GHz + 3×3.2 GHz + 2×3.0 GHz + 2×2.3 GHz",
    processor_gpu: "Adreno 750",
    processor_fabrication: "4 نانومتر",
    antutu_score: "2,200,000",
    memory_storage: "256/512GB",
    memory_ram: "12/16GB",
    memory_type: "UFS 4.0",
    memory_sd_card: "لا",
    camera_main: "50 ميجابكسل، f/1.8، OIS، PDAF",
    camera_ultrawide: "8 ميجابكسل، f/2.2، 112°",
    camera_telephoto: "50 ميجابكسل، f/2.0، تقريب بصري 2×",
    camera_front: "16 ميجابكسل، f/2.4",
    camera_video: "4K@60fps، 1080p@240fps",
    audio_speakers: "ستيريو",
    audio_jack: "لا",
    connectivity_sim: "Nano-SIM + eSIM",
    connectivity_network: "5G SA/NSA",
    connectivity_wifi: "Wi-Fi 7",
    connectivity_bluetooth: "5.4",
    connectivity_nfc: "نعم",
    connectivity_gps: "GPS، GLONASS، Galileo، BeiDou",
    protection_water: "IP65",
    protection_standard: "IP65",
    battery_capacity: "6000 مللي أمبير",
    battery_charging: "80 واط",
    battery_wireless: "لا",
    battery_reverse: "لا",
    software_os: "Android 15",
    software_ui: "OxygenOS 15",
    sensor_fingerprint: "بصري تحت الشاشة",
    sensor_face_unlock: "نعم",
    sensor_gyroscope: "نعم",
    sensor_compass: "نعم",
    sensor_proximity: "نعم",
    sensor_light: "نعم",
    sensor_other: "مقياس التسارع"
  },

  // ==================== HONOR 2025 ====================

  // Honor Magic 7 Pro
  {
    slug: "honor-magic-7-pro",
    name: "Honor Magic 7 Pro",
    name_ar: "هونر ماجيك 7 برو",
    brand: "Honor",
    year: 2025,
    release_date: "نوفمبر 2024",
    image: "https://fdn2.gsmarena.com/vv/bigpic/honor-magic7-pro.jpg",
    status: "published",
    quick_screen: "6.8 بوصة LTPO OLED، 120Hz",
    quick_processor: "Snapdragon 8 Elite",
    quick_camera: "200 ميجابكسل بيريسكوب",
    quick_front_camera: "50 ميجابكسل 3D TOF",
    quick_memory: "256/512GB/1TB مع 12/16GB رام",
    quick_battery: "5850 مللي أمبير، شحن 100 واط",
    design_height: "162.7 ملم",
    design_width: "77.1 ملم",
    design_thickness: "8.8 ملم",
    design_weight: "223 جرام",
    design_materials: "زجاج NanoCrystal Shield، إطار زجاج",
    design_colors: "رمادي قمري، أزرق نسيم، أسود، أبيض",
    design_frame: "إطار معدني",
    screen_type: "LTPO OLED",
    screen_size: "6.8 بوصة",
    screen_resolution: "1280 × 2800 بكسل",
    screen_ppi: "453 بكسل لكل بوصة",
    screen_refresh_rate: "1-120Hz",
    screen_brightness: "5000 نيت (ذروة)",
    screen_protection: "NanoCrystal Shield",
    processor_name: "Qualcomm Snapdragon 8 Elite (3nm)",
    processor_cores: "ثماني النواة",
    processor_frequency: "2×4.32 GHz Oryon V2 + 6×3.53 GHz Oryon V2",
    processor_gpu: "Adreno 830",
    processor_fabrication: "3 نانومتر",
    antutu_score: "2,767,000",
    memory_storage: "256/512GB/1TB",
    memory_ram: "12/16GB",
    memory_type: "UFS 4.0",
    memory_sd_card: "لا",
    camera_main: "50 ميجابكسل، f/1.4-2.0، OIS، PDAF متعدد الاتجاهات",
    camera_ultrawide: "50 ميجابكسل، f/2.0، 122°، Dual Pixel PDAF",
    camera_telephoto: "200 ميجابكسل بيريسكوب، f/2.6، 72mm، تقريب بصري 3×، OIS",
    camera_front: "50 ميجابكسل، f/2.0، TOF 3D",
    camera_video: "4K@60fps، HDR، 10-bit",
    audio_speakers: "ستيريو كبير السعة",
    audio_jack: "لا",
    connectivity_sim: "Nano-SIM + eSIM",
    connectivity_network: "5G SA/NSA",
    connectivity_wifi: "Wi-Fi 7",
    connectivity_bluetooth: "5.4",
    connectivity_nfc: "نعم",
    connectivity_gps: "GPS (L1+L5)، GLONASS، Galileo، BeiDou",
    protection_water: "IP68/IP69",
    protection_standard: "IP68/IP69",
    battery_capacity: "5850 مللي أمبير (عالمي)، 5270 مللي أمبير (أوروبا)",
    battery_charging: "100 واط سلكي (100% في 33 دقيقة)",
    battery_wireless: "80 واط (100% في 44 دقيقة)",
    battery_reverse: "5 واط لاسلكي عكسي",
    software_os: "Android 15",
    software_ui: "MagicOS 10",
    sensor_fingerprint: "بالموجات فوق الصوتية تحت الشاشة",
    sensor_face_unlock: "Face ID 3D",
    sensor_gyroscope: "نعم",
    sensor_compass: "نعم",
    sensor_proximity: "نعم",
    sensor_light: "نعم",
    sensor_other: "مقياس التسارع، الأشعة تحت الحمراء"
  },

  // ==================== REALME 2025 ====================

  // Realme GT 7 Pro
  {
    slug: "realme-gt-7-pro",
    name: "Realme GT 7 Pro",
    name_ar: "ريلمي GT 7 برو",
    brand: "Realme",
    year: 2025,
    release_date: "نوفمبر 2024",
    image: "https://fdn2.gsmarena.com/vv/bigpic/realme-gt7-pro.jpg",
    status: "published",
    quick_screen: "6.78 بوصة LTPO AMOLED، 120Hz",
    quick_processor: "Snapdragon 8 Elite",
    quick_camera: "50 ميجابكسل Sony IMX906",
    quick_front_camera: "16 ميجابكسل",
    quick_memory: "256/512GB مع 12/16GB رام",
    quick_battery: "6500 مللي أمبير، شحن 120 واط",
    design_height: "162.5 ملم",
    design_width: "76.0 ملم",
    design_thickness: "8.6 ملم",
    design_weight: "222 جرام",
    design_materials: "زجاج Armor Glass، إطار ألمنيوم",
    design_colors: "أسود مارس، رمادي جالاكسي، برتقالي",
    design_frame: "إطار ألمنيوم",
    screen_type: "LTPO AMOLED",
    screen_size: "6.78 بوصة",
    screen_resolution: "1264 × 2780 بكسل",
    screen_ppi: "450 بكسل لكل بوصة",
    screen_refresh_rate: "1-120Hz",
    screen_brightness: "6500 نيت (ذروة)",
    screen_protection: "Armor Glass",
    processor_name: "Qualcomm Snapdragon 8 Elite (3nm)",
    processor_cores: "ثماني النواة",
    processor_frequency: "2×4.32 GHz + 6×3.53 GHz",
    processor_gpu: "Adreno 830",
    processor_fabrication: "3 نانومتر",
    antutu_score: "2,800,000",
    memory_storage: "256/512GB",
    memory_ram: "12/16GB",
    memory_type: "UFS 4.0",
    memory_sd_card: "لا",
    camera_main: "50 ميجابكسل Sony IMX906، f/1.8، OIS",
    camera_ultrawide: "8 ميجابكسل، f/2.2، 112°",
    camera_telephoto: "50 ميجابكسل بيريسكوب، f/2.8، تقريب بصري 3×، OIS",
    camera_front: "16 ميجابكسل، f/2.5",
    camera_video: "4K@60fps، Dolby Vision",
    audio_speakers: "ستيريو",
    audio_jack: "لا",
    connectivity_sim: "Nano-SIM + eSIM",
    connectivity_network: "5G SA/NSA",
    connectivity_wifi: "Wi-Fi 7",
    connectivity_bluetooth: "5.4",
    connectivity_nfc: "نعم",
    connectivity_gps: "GPS، GLONASS، Galileo، BeiDou، NavIC",
    protection_water: "IP69",
    protection_standard: "IP68/IP69",
    battery_capacity: "6500 مللي أمبير",
    battery_charging: "120 واط (50% في 8 دقائق)",
    battery_wireless: "لا",
    battery_reverse: "لا",
    software_os: "Android 15",
    software_ui: "Realme UI 6.0",
    sensor_fingerprint: "بالموجات فوق الصوتية تحت الشاشة",
    sensor_face_unlock: "نعم",
    sensor_gyroscope: "نعم",
    sensor_compass: "نعم",
    sensor_proximity: "نعم",
    sensor_light: "نعم",
    sensor_other: "مقياس التسارع"
  },

  // ==================== NOTHING 2025 ====================

  // Nothing Phone (3)
  {
    slug: "nothing-phone-3",
    name: "Nothing Phone (3)",
    name_ar: "ناثينج فون (3)",
    brand: "Nothing",
    year: 2025,
    release_date: "مارس 2025",
    image: "https://fdn2.gsmarena.com/vv/bigpic/nothing-phone-3.jpg",
    status: "published",
    quick_screen: "6.7 بوصة LTPO OLED، 120Hz",
    quick_processor: "Snapdragon 8s Gen 3",
    quick_camera: "50 ميجابكسل رئيسية",
    quick_front_camera: "32 ميجابكسل",
    quick_memory: "256/512GB مع 12GB رام",
    quick_battery: "5000 مللي أمبير، شحن 65 واط",
    design_height: "162.0 ملم",
    design_width: "75.5 ملم",
    design_thickness: "8.3 ملم",
    design_weight: "195 جرام",
    design_materials: "زجاج Gorilla Glass، إطار ألمنيوم معاد تدويره",
    design_colors: "أسود، أبيض",
    design_frame: "إطار ألمنيوم معاد تدويره 100%",
    screen_type: "LTPO OLED",
    screen_size: "6.7 بوصة",
    screen_resolution: "1080 × 2400 بكسل",
    screen_ppi: "393 بكسل لكل بوصة",
    screen_refresh_rate: "1-120Hz",
    screen_brightness: "2000 نيت",
    screen_protection: "Corning Gorilla Glass",
    processor_name: "Qualcomm Snapdragon 8s Gen 3 (4nm)",
    processor_cores: "ثماني النواة",
    processor_frequency: "1×3.0 GHz + 4×2.8 GHz + 3×2.0 GHz",
    processor_gpu: "Adreno 735",
    processor_fabrication: "4 نانومتر",
    antutu_score: "1,600,000",
    memory_storage: "256/512GB",
    memory_ram: "12GB",
    memory_type: "UFS 4.0",
    memory_sd_card: "لا",
    camera_main: "50 ميجابكسل، f/1.8، OIS، PDAF",
    camera_ultrawide: "50 ميجابكسل، f/2.2، 114°",
    camera_telephoto: "50 ميجابكسل، f/2.5، تقريب بصري 3×",
    camera_front: "32 ميجابكسل، f/2.0",
    camera_video: "4K@60fps، 1080p@120fps",
    audio_speakers: "ستيريو",
    audio_jack: "لا",
    connectivity_sim: "Nano-SIM + eSIM",
    connectivity_network: "5G SA/NSA",
    connectivity_wifi: "Wi-Fi 7",
    connectivity_bluetooth: "5.3",
    connectivity_nfc: "نعم",
    connectivity_gps: "GPS، GLONASS، Galileo، BeiDou",
    protection_water: "IP54",
    protection_standard: "IP54",
    battery_capacity: "5000 مللي أمبير",
    battery_charging: "65 واط",
    battery_wireless: "15 واط",
    battery_reverse: "5 واط",
    software_os: "Android 15",
    software_ui: "Nothing OS 3.0",
    sensor_fingerprint: "بصري تحت الشاشة",
    sensor_face_unlock: "نعم",
    sensor_gyroscope: "نعم",
    sensor_compass: "نعم",
    sensor_proximity: "نعم",
    sensor_light: "نعم",
    sensor_other: "مقياس التسارع، Glyph Interface"
  },

  // ==================== OPPO 2025 ====================

  // OPPO Find X8 Pro
  {
    slug: "oppo-find-x8-pro",
    name: "OPPO Find X8 Pro",
    name_ar: "أوبو فايند X8 برو",
    brand: "OPPO",
    year: 2025,
    release_date: "نوفمبر 2024",
    image: "https://fdn2.gsmarena.com/vv/bigpic/oppo-find-x8-pro.jpg",
    status: "published",
    quick_screen: "6.78 بوصة LTPO AMOLED، 120Hz",
    quick_processor: "MediaTek Dimensity 9400",
    quick_camera: "50 ميجابكسل Hasselblad",
    quick_front_camera: "32 ميجابكسل",
    quick_memory: "256/512GB مع 16GB رام",
    quick_battery: "5910 مللي أمبير، شحن 80 واط",
    design_height: "162.3 ملم",
    design_width: "76.2 ملم",
    design_thickness: "8.2 ملم",
    design_weight: "215 جرام",
    design_materials: "زجاج Gorilla Glass 7i، إطار ألمنيوم",
    design_colors: "أسود فضاء، أبيض لؤلؤي",
    design_frame: "إطار ألمنيوم",
    screen_type: "LTPO AMOLED",
    screen_size: "6.78 بوصة",
    screen_resolution: "1264 × 2780 بكسل",
    screen_ppi: "450 بكسل لكل بوصة",
    screen_refresh_rate: "1-120Hz",
    screen_brightness: "4500 نيت",
    screen_protection: "Corning Gorilla Glass 7i",
    processor_name: "MediaTek Dimensity 9400 (3nm)",
    processor_cores: "ثماني النواة",
    processor_frequency: "1×3.63 GHz + 3×3.3 GHz + 4×2.4 GHz",
    processor_gpu: "Immortalis-G925 MC12",
    processor_fabrication: "3 نانومتر",
    antutu_score: "2,600,000",
    memory_storage: "256/512GB",
    memory_ram: "16GB",
    memory_type: "UFS 4.0",
    memory_sd_card: "لا",
    camera_main: "50 ميجابكسل Hasselblad، f/1.6، OIS",
    camera_ultrawide: "50 ميجابكسل، f/2.0، 120°",
    camera_telephoto: "50 ميجابكسل بيريسكوب، f/2.6، تقريب بصري 3× + 50 ميجابكسل، f/4.3، تقريب 6×",
    camera_front: "32 ميجابكسل، f/2.4",
    camera_video: "4K@60fps، Dolby Vision، Live Photo",
    audio_speakers: "ستيريو",
    audio_jack: "لا",
    connectivity_sim: "Nano-SIM + eSIM",
    connectivity_network: "5G SA/NSA",
    connectivity_wifi: "Wi-Fi 7",
    connectivity_bluetooth: "5.4",
    connectivity_nfc: "نعم",
    connectivity_gps: "GPS، GLONASS، Galileo، BeiDou، NavIC",
    protection_water: "IP69",
    protection_standard: "IP68/IP69",
    battery_capacity: "5910 مللي أمبير",
    battery_charging: "80 واط سلكي",
    battery_wireless: "50 واط AIRVOOC",
    battery_reverse: "10 واط",
    software_os: "Android 15",
    software_ui: "ColorOS 15",
    sensor_fingerprint: "بالموجات فوق الصوتية تحت الشاشة",
    sensor_face_unlock: "نعم",
    sensor_gyroscope: "نعم",
    sensor_compass: "نعم",
    sensor_proximity: "نعم",
    sensor_light: "نعم",
    sensor_other: "مقياس التسارع، الأشعة تحت الحمراء"
  },

  // ==================== VIVO 2025 ====================

  // Vivo X200 Pro
  {
    slug: "vivo-x200-pro",
    name: "Vivo X200 Pro",
    name_ar: "فيفو X200 برو",
    brand: "Vivo",
    year: 2025,
    release_date: "أكتوبر 2024",
    image: "https://fdn2.gsmarena.com/vv/bigpic/vivo-x200-pro.jpg",
    status: "published",
    quick_screen: "6.78 بوصة LTPO AMOLED، 120Hz",
    quick_processor: "MediaTek Dimensity 9400",
    quick_camera: "200 ميجابكسل ZEISS APO",
    quick_front_camera: "32 ميجابكسل",
    quick_memory: "256/512GB مع 16GB رام",
    quick_battery: "6000 مللي أمبير، شحن 90 واط",
    design_height: "164.0 ملم",
    design_width: "75.6 ملم",
    design_thickness: "8.5 ملم",
    design_weight: "228 جرام",
    design_materials: "زجاج Schott Xensation، إطار ألمنيوم",
    design_colors: "أسود تيتانيوم، أزرق",
    design_frame: "إطار ألمنيوم",
    screen_type: "LTPO AMOLED",
    screen_size: "6.78 بوصة",
    screen_resolution: "1260 × 2800 بكسل",
    screen_ppi: "453 بكسل لكل بوصة",
    screen_refresh_rate: "1-120Hz",
    screen_brightness: "4500 نيت",
    screen_protection: "Schott Xensation",
    processor_name: "MediaTek Dimensity 9400 (3nm)",
    processor_cores: "ثماني النواة",
    processor_frequency: "1×3.63 GHz + 3×3.3 GHz + 4×2.4 GHz",
    processor_gpu: "Immortalis-G925 MC12",
    processor_fabrication: "3 نانومتر",
    antutu_score: "2,650,000",
    memory_storage: "256/512GB",
    memory_ram: "16GB",
    memory_type: "UFS 4.0",
    memory_sd_card: "لا",
    camera_main: "50 ميجابكسل ZEISS، f/1.6، OIS",
    camera_ultrawide: "50 ميجابكسل، f/2.0، 119°",
    camera_telephoto: "200 ميجابكسل ZEISS APO بيريسكوب، f/2.7، تقريب بصري 3.7×، OIS",
    camera_front: "32 ميجابكسل، f/2.0",
    camera_video: "8K@30fps، 4K@120fps، ZEISS Cinematic",
    audio_speakers: "ستيريو",
    audio_jack: "لا",
    connectivity_sim: "Nano-SIM + eSIM",
    connectivity_network: "5G SA/NSA",
    connectivity_wifi: "Wi-Fi 7",
    connectivity_bluetooth: "5.4",
    connectivity_nfc: "نعم",
    connectivity_gps: "GPS، GLONASS، Galileo، BeiDou، NavIC",
    protection_water: "IP69",
    protection_standard: "IP68/IP69",
    battery_capacity: "6000 مللي أمبير",
    battery_charging: "90 واط سلكي",
    battery_wireless: "30 واط",
    battery_reverse: "5 واط",
    software_os: "Android 15",
    software_ui: "OriginOS 5 / Funtouch OS 15",
    sensor_fingerprint: "بالموجات فوق الصوتية تحت الشاشة",
    sensor_face_unlock: "نعم",
    sensor_gyroscope: "نعم",
    sensor_compass: "نعم",
    sensor_proximity: "نعم",
    sensor_light: "نعم",
    sensor_other: "مقياس التسارع، الأشعة تحت الحمراء"
  },

  // ==================== HUAWEI 2025 ====================

  // Huawei Pura 80 Pro
  {
    slug: "huawei-pura-80-pro",
    name: "Huawei Pura 80 Pro",
    name_ar: "هواوي بورا 80 برو",
    brand: "Huawei",
    year: 2025,
    release_date: "أبريل 2025",
    image: "https://fdn2.gsmarena.com/vv/bigpic/huawei-pura-80-pro.jpg",
    status: "published",
    quick_screen: "6.8 بوصة LTPO OLED، 120Hz",
    quick_processor: "Kirin 9100",
    quick_camera: "50 ميجابكسل XMAGE",
    quick_front_camera: "13 ميجابكسل + TOF 3D",
    quick_memory: "256/512GB/1TB مع 12/16GB رام",
    quick_battery: "5200 مللي أمبير، شحن 100 واط",
    design_height: "163.5 ملم",
    design_width: "76.8 ملم",
    design_thickness: "8.4 ملم",
    design_weight: "218 جرام",
    design_materials: "زجاج Kunlun Glass 2، إطار ألمنيوم",
    design_colors: "أسود، أبيض، أخضر، ذهبي",
    design_frame: "إطار ألمنيوم",
    screen_type: "LTPO OLED",
    screen_size: "6.8 بوصة",
    screen_resolution: "1260 × 2844 بكسل",
    screen_ppi: "460 بكسل لكل بوصة",
    screen_refresh_rate: "1-120Hz",
    screen_brightness: "2500 نيت",
    screen_protection: "Kunlun Glass 2",
    processor_name: "HiSilicon Kirin 9100 (7nm)",
    processor_cores: "ثماني النواة",
    processor_frequency: "1×3.2 GHz + 3×2.8 GHz + 4×2.0 GHz",
    processor_gpu: "Maleoon 920",
    processor_fabrication: "7 نانومتر",
    antutu_score: "1,200,000",
    memory_storage: "256/512GB/1TB",
    memory_ram: "12/16GB",
    memory_type: "UFS 3.1",
    memory_sd_card: "نعم، NM Card حتى 256GB",
    camera_main: "50 ميجابكسل XMAGE، f/1.4-4.0 عدسة متغيرة، OIS",
    camera_ultrawide: "40 ميجابكسل، f/2.2، 120°",
    camera_telephoto: "48 ميجابكسل بيريسكوب، f/3.0، تقريب بصري 3.5×، OIS",
    camera_front: "13 ميجابكسل، f/2.4 + TOF 3D",
    camera_video: "4K@60fps، 10-bit HDR، Super Slow-mo",
    audio_speakers: "ستيريو",
    audio_jack: "لا",
    connectivity_sim: "Nano-SIM + Nano-SIM أو eSIM",
    connectivity_network: "5G SA/NSA",
    connectivity_wifi: "Wi-Fi 6E",
    connectivity_bluetooth: "5.2",
    connectivity_nfc: "نعم",
    connectivity_gps: "GPS، GLONASS، Galileo، BeiDou، QZSS",
    protection_water: "IP68",
    protection_standard: "IP68",
    battery_capacity: "5200 مللي أمبير",
    battery_charging: "100 واط سلكي",
    battery_wireless: "80 واط",
    battery_reverse: "20 واط",
    software_os: "HarmonyOS 5",
    software_ui: "HarmonyOS 5",
    sensor_fingerprint: "بالموجات فوق الصوتية تحت الشاشة",
    sensor_face_unlock: "3D Face Recognition",
    sensor_gyroscope: "نعم",
    sensor_compass: "نعم",
    sensor_proximity: "نعم",
    sensor_light: "نعم",
    sensor_other: "مقياس التسارع، البارومتر، مقياس الحرارة، الأشعة تحت الحمراء"
  }
];

async function seedPhones() {
  console.log("Starting to seed 2025-2026 phones...");
  console.log(`Total phones to process: ${phones2025_2026.length}`);
  let successCount = 0;
  let errorCount = 0;

  for (const phoneData of phones2025_2026) {
    try {
      const { data: brandData, error: brandError } = await supabase
        .from("brands")
        .select("id")
        .eq("name", phoneData.brand)
        .single();

      if (brandError || !brandData) {
        // Try to create the brand if it doesn't exist
        const { data: newBrand, error: createBrandError } = await supabase
          .from("brands")
          .insert([{ 
            name: phoneData.brand, 
            slug: phoneData.brand.toLowerCase().replace(/\s+/g, '-'),
            logo: `https://fdn2.gsmarena.com/vv/bigpic/${phoneData.brand.toLowerCase()}-logo.jpg`
          }])
          .select()
          .single();
        
        if (createBrandError) {
          console.error(`Brand ${phoneData.brand} not found and couldn't be created. Skipping ${phoneData.name}`);
          errorCount++;
          continue;
        }
        
        const brandId = newBrand.id;
        const { brand: _brand, ...phoneFields } = phoneData;
        const phonePayload = {
          ...phoneFields,
          brand_id: brandId,
        };

        const { error } = await supabase.from("phones").insert([phonePayload]);
        if (error) throw error;
        console.log(`✓ Created brand ${phoneData.brand} and inserted: ${phoneData.name}`);
        successCount++;
        continue;
      }

      const { data: existingPhone } = await supabase
        .from("phones")
        .select("id")
        .eq("slug", phoneData.slug)
        .maybeSingle();

      const { brand: _brand, ...phoneFields } = phoneData;
      const phonePayload = {
        ...phoneFields,
        brand_id: brandData.id,
      };

      if (existingPhone) {
        const { error } = await supabase
          .from("phones")
          .update({ ...phonePayload, updated_at: new Date().toISOString() })
          .eq("id", existingPhone.id);

        if (error) throw error;
        console.log(`✓ Updated: ${phoneData.name}`);
      } else {
        const { error } = await supabase
          .from("phones")
          .insert([phonePayload]);

        if (error) throw error;
        console.log(`✓ Inserted: ${phoneData.name}`);
      }
      successCount++;
    } catch (error) {
      console.error(`✗ Error processing ${phoneData.name}:`, error);
      errorCount++;
    }
  }

  console.log(`\n========================================`);
  console.log(`Seeding completed!`);
  console.log(`Success: ${successCount}/${phones2025_2026.length}`);
  console.log(`Errors: ${errorCount}`);
  console.log(`========================================`);
  process.exit(0);
}

seedPhones();
