import "dotenv/config";
import bcrypt from "bcryptjs";
import { db } from "./db.js";
import { brands, phones, admin_users } from "./schema.js";
import { eq } from "drizzle-orm";

const brandsList = [
  { slug: "apple", name: "Apple", name_ar: "آبل", logo: "https://fdn2.gsmarena.com/imgroot/reviews/23/apple-iphone-15-pro-max/-347x151/lifestyle.jpg", color: "#A6B1B7" },
  { slug: "samsung", name: "Samsung", name_ar: "سامسونج", logo: "https://fdn2.gsmarena.com/imgroot/static/headers/logo.png", color: "#1428A0" },
  { slug: "xiaomi", name: "Xiaomi", name_ar: "شاومي", logo: "https://fdn2.gsmarena.com/imgroot/static/headers/logo.png", color: "#FF6900" },
  { slug: "google", name: "Google", name_ar: "جوجل", logo: "https://fdn2.gsmarena.com/imgroot/static/headers/logo.png", color: "#4285F4" },
  { slug: "oppo", name: "Oppo", name_ar: "أوبو", logo: "https://fdn2.gsmarena.com/imgroot/static/headers/logo.png", color: "#00A469" },
  { slug: "oneplus", name: "OnePlus", name_ar: "ون بلس", logo: "https://fdn2.gsmarena.com/imgroot/static/headers/logo.png", color: "#EB0028" },
  { slug: "vivo", name: "Vivo", name_ar: "فيفو", logo: "https://fdn2.gsmarena.com/imgroot/static/headers/logo.png", color: "#0066FF" },
  { slug: "honor", name: "Honor", name_ar: "هونر", logo: "https://fdn2.gsmarena.com/imgroot/static/headers/logo.png", color: "#0086D1" },
  { slug: "huawei", name: "Huawei", name_ar: "هواوي", logo: "https://fdn2.gsmarena.com/imgroot/static/headers/logo.png", color: "#C8102E" },
];

const phones2025 = [
  {
    brand: "Apple",
    name: "iPhone 17 Pro Max",
    name_ar: "آيفون 17 برو ماكس",
    slug: "apple-iphone-17-pro-max",
    year: 2025,
    release_date: "سبتمبر 2025",
    image: "https://fdn2.gsmarena.com/vv/bigpic/apple-iphone-17-pro-max.jpg",
    quick_screen: '6.9" LTPO Super Retina XDR OLED',
    quick_processor: "Apple A19 Pro (3nm)",
    quick_camera: "48 MP + 48 MP + 12 MP",
    quick_front_camera: "12 MP",
    quick_memory: "256/512GB/1TB, 8GB RAM",
    quick_battery: "4700 mAh",
    design_height: "163.0 mm",
    design_width: "77.8 mm",
    design_thickness: "8.3 mm",
    design_weight: "228 g",
    design_materials: "زجاج أمامي وخلفي (Ceramic Shield)، إطار تيتانيوم",
    design_colors: "تيتانيوم طبيعي، أزرق، أبيض، أسود",
    design_frame: "تيتانيوم",
    screen_type: "LTPO Super Retina XDR OLED، HDR10، Dolby Vision، 120Hz، 2000 nits",
    screen_size: '6.9"',
    screen_resolution: "1320 x 2868 بكسل",
    screen_ppi: "460 ppi",
    screen_refresh_rate: "120Hz",
    screen_brightness: "2000 nits (HBM)، 2800 nits (peak)",
    screen_protection: "Ceramic Shield (الجيل الثاني)",
    processor_name: "Apple A19 Pro",
    processor_cores: "6 أنوية (2x3.8 GHz + 4x2.6 GHz)",
    processor_frequency: "3.8 GHz",
    processor_gpu: "Apple GPU 6-core",
    processor_fabrication: "3 nm",
    antutu_score: "2100000",
    memory_storage: "256GB، 512GB، 1TB",
    memory_ram: "8GB",
    memory_type: "NVMe",
    memory_sd_card: "لا",
    camera_main: "48 MP، f/1.8، 24mm (عريضة)، PDAF، OIS",
    camera_ultrawide: "48 MP، f/2.2، 13mm، 120°",
    camera_telephoto: "12 MP، f/2.8، 120mm، PDAF، OIS، 5x optical zoom",
    camera_front: "12 MP، f/1.9، 23mm (عريضة)، PDAF",
    camera_video: "4K@24/25/30/60fps، 1080p@25/30/60/120/240fps، HDR، Dolby Vision HDR",
    audio_speakers: "ستيريو",
    audio_jack: "لا",
    connectivity_sim: "Nano-SIM و eSIM",
    connectivity_network: "5G",
    connectivity_wifi: "Wi-Fi 7",
    connectivity_bluetooth: "5.4",
    connectivity_nfc: "نعم",
    connectivity_gps: "GPS، GLONASS، GALILEO، QZSS، BDS",
    protection_water: "IP68",
    protection_standard: "مقاوم للماء حتى 6 متر لمدة 30 دقيقة",
    battery_capacity: "4700 mAh",
    battery_charging: "شحن سلكي 40W، 50% في 30 دقيقة",
    battery_wireless: "MagSafe 25W، Qi2 15W",
    battery_reverse: "نعم",
    software_os: "iOS 19",
    software_ui: "iOS 19",
    sensor_fingerprint: "لا",
    sensor_face_unlock: "نعم (Face ID)",
    sensor_gyroscope: "نعم",
    sensor_compass: "نعم",
    sensor_proximity: "نعم",
    sensor_light: "نعم",
    sensor_other: "مقياس تسارع، باروميتر، Ultra Wideband 2",
    status: "published"
  },
  {
    brand: "Google",
    name: "Pixel 10 Pro",
    name_ar: "بكسل 10 برو",
    slug: "google-pixel-10-pro",
    year: 2025,
    release_date: "أكتوبر 2025",
    image: "https://fdn2.gsmarena.com/vv/bigpic/google-pixel-10-pro.jpg",
    quick_screen: '6.8" LTPO OLED 120Hz',
    quick_processor: "Google Tensor G5 (3nm)",
    quick_camera: "50 MP + 48 MP + 48 MP",
    quick_front_camera: "42 MP",
    quick_memory: "256/512GB, 12/16GB RAM",
    quick_battery: "5100 mAh",
    design_height: "163.0 mm",
    design_width: "76.6 mm",
    design_thickness: "8.9 mm",
    design_weight: "221 g",
    design_materials: "زجاج Gorilla Glass Victus 3، إطار ألمنيوم",
    design_colors: "أسود، أبيض، أزرق، وردي",
    design_frame: "ألمنيوم",
    screen_type: "LTPO OLED، HDR10+، 120Hz",
    screen_size: '6.8"',
    screen_resolution: "1344 x 2992 بكسل",
    screen_ppi: "486 ppi",
    screen_refresh_rate: "1-120Hz",
    screen_brightness: "2400 nits (peak)",
    screen_protection: "Corning Gorilla Glass Victus 3",
    processor_name: "Google Tensor G5",
    processor_cores: "9 أنوية",
    processor_frequency: "3.4 GHz",
    processor_gpu: "Mali-G925",
    processor_fabrication: "3 nm",
    antutu_score: "1450000",
    memory_storage: "256GB، 512GB",
    memory_ram: "12GB، 16GB",
    memory_type: "UFS 4.0",
    memory_sd_card: "لا",
    camera_main: "50 MP، f/1.7، 25mm (عريضة)، PDAF، Laser AF، OIS",
    camera_ultrawide: "48 MP، f/1.9، 126°",
    camera_telephoto: "48 MP، f/2.8، 113mm، PDAF، OIS، 5x optical zoom",
    camera_front: "42 MP، f/2.2، 17mm (ultrawide)، PDAF",
    camera_video: "8K@30fps، 4K@30/60fps، 1080p@60/120/240fps",
    audio_speakers: "ستيريو",
    audio_jack: "لا",
    connectivity_sim: "Nano-SIM و eSIM",
    connectivity_network: "5G",
    connectivity_wifi: "Wi-Fi 7",
    connectivity_bluetooth: "5.4",
    connectivity_nfc: "نعم",
    connectivity_gps: "GPS، GLONASS، GALILEO، QZSS، BDS",
    protection_water: "IP68",
    protection_standard: "مقاوم للماء والغبار",
    battery_capacity: "5100 mAh",
    battery_charging: "45W سلكي، 50% في 25 دقيقة",
    battery_wireless: "23W لاسلكي",
    battery_reverse: "نعم (12W)",
    software_os: "Android 16",
    software_ui: "Pixel UI",
    sensor_fingerprint: "نعم (تحت الشاشة، بصري)",
    sensor_face_unlock: "نعم",
    sensor_gyroscope: "نعم",
    sensor_compass: "نعم",
    sensor_proximity: "نعم",
    sensor_light: "نعم",
    sensor_other: "مقياس تسارع، باروميتر، ميزان حرارة",
    status: "published"
  },
  {
    brand: "OnePlus",
    name: "OnePlus 13 Pro",
    name_ar: "ون بلس 13 برو",
    slug: "oneplus-13-pro",
    year: 2025,
    release_date: "يناير 2025",
    image: "https://fdn2.gsmarena.com/vv/bigpic/oneplus-13-pro.jpg",
    quick_screen: '6.82" LTPO AMOLED 120Hz',
    quick_processor: "Snapdragon 8 Elite",
    quick_camera: "50 MP + 50 MP + 64 MP (Hasselblad)",
    quick_front_camera: "32 MP",
    quick_memory: "256/512GB/1TB, 12/16/24GB RAM",
    quick_battery: "6000 mAh",
    design_height: "163.3 mm",
    design_width: "76.0 mm",
    design_thickness: "8.9 mm",
    design_weight: "213 g",
    design_materials: "زجاج أمامي وخلفي، إطار ألمنيوم",
    design_colors: "أسود، أخضر، فضي",
    design_frame: "ألمنيوم",
    screen_type: "LTPO AMOLED، 1B colors، 120Hz، Dolby Vision، HDR10+",
    screen_size: '6.82"',
    screen_resolution: "1440 x 3168 بكسل",
    screen_ppi: "510 ppi",
    screen_refresh_rate: "1-120Hz",
    screen_brightness: "4500 nits (peak)",
    screen_protection: "Ceramic Guard",
    processor_name: "Snapdragon 8 Elite",
    processor_cores: "8 أنوية (2x4.32 GHz + 6x3.53 GHz)",
    processor_frequency: "4.32 GHz",
    processor_gpu: "Adreno 830",
    processor_fabrication: "3 nm",
    antutu_score: "2800000",
    memory_storage: "256GB، 512GB، 1TB",
    memory_ram: "12GB، 16GB، 24GB",
    memory_type: "UFS 4.0",
    memory_sd_card: "لا",
    camera_main: "50 MP، f/1.6، 23mm (عريضة)، PDAF، OIS، Hasselblad",
    camera_ultrawide: "50 MP، f/2.0، 15mm، 120°",
    camera_telephoto: "64 MP، f/2.6، 73mm، PDAF، OIS، 3x optical zoom",
    camera_front: "32 MP، f/2.4، 21mm (عريضة)",
    camera_video: "8K@30fps، 4K@30/60/120fps، 1080p@30/60/240fps، HDR",
    audio_speakers: "ستيريو",
    audio_jack: "لا",
    connectivity_sim: "Dual SIM (Nano-SIM، dual stand-by)",
    connectivity_network: "5G",
    connectivity_wifi: "Wi-Fi 7",
    connectivity_bluetooth: "5.4",
    connectivity_nfc: "نعم",
    connectivity_gps: "GPS، GLONASS، GALILEO، QZSS، BDS، NavIC",
    protection_water: "IP69",
    protection_standard: "مقاوم للماء والغبار وضغط البخار",
    battery_capacity: "6000 mAh",
    battery_charging: "100W سلكي، 100% في 26 دقيقة",
    battery_wireless: "50W لاسلكي",
    battery_reverse: "نعم (10W)",
    software_os: "Android 15",
    software_ui: "OxygenOS 15",
    sensor_fingerprint: "نعم (تحت الشاشة، بصري)",
    sensor_face_unlock: "نعم",
    sensor_gyroscope: "نعم",
    sensor_compass: "نعم",
    sensor_proximity: "نعم",
    sensor_light: "نعم",
    sensor_other: "مقياس تسارع، مستشعر الأشعة تحت الحمراء",
    status: "published"
  },
  {
    brand: "Oppo",
    name: "Find X8 Pro",
    name_ar: "فايند اكس 8 برو",
    slug: "oppo-find-x8-pro",
    year: 2025,
    release_date: "نوفمبر 2024",
    image: "https://fdn2.gsmarena.com/vv/bigpic/oppo-find-x8-pro.jpg",
    quick_screen: '6.78" LTPO AMOLED 120Hz',
    quick_processor: "MediaTek Dimensity 9400",
    quick_camera: "50 MP + 50 MP + 50 MP + 50 MP (Hasselblad)",
    quick_front_camera: "32 MP",
    quick_memory: "256/512GB/1TB, 12/16GB RAM",
    quick_battery: "5910 mAh",
    design_height: "162.3 mm",
    design_width: "76.7 mm",
    design_thickness: "8.2 mm",
    design_weight: "215 g",
    design_materials: "زجاج أمامي وخلفي، إطار ألمنيوم",
    design_colors: "أسود، أبيض، أزرق",
    design_frame: "ألمنيوم",
    screen_type: "LTPO AMOLED، 1B colors، 120Hz، Dolby Vision، HDR10+",
    screen_size: '6.78"',
    screen_resolution: "1264 x 2780 بكسل",
    screen_ppi: "450 ppi",
    screen_refresh_rate: "1-120Hz",
    screen_brightness: "4500 nits (peak)",
    screen_protection: "Corning Gorilla Glass Victus 2",
    processor_name: "MediaTek Dimensity 9400",
    processor_cores: "8 أنوية (1x3.63 GHz + 3x3.3 GHz + 4x2.4 GHz)",
    processor_frequency: "3.63 GHz",
    processor_gpu: "Immortalis-G925",
    processor_fabrication: "3 nm",
    antutu_score: "2900000",
    memory_storage: "256GB، 512GB، 1TB",
    memory_ram: "12GB، 16GB",
    memory_type: "UFS 4.0",
    memory_sd_card: "لا",
    camera_main: "50 MP، f/1.6، 23mm (عريضة)، PDAF، Laser AF، OIS، Hasselblad",
    camera_ultrawide: "50 MP، f/2.0، 15mm، 120°، PDAF",
    camera_telephoto: "50 MP، f/2.6، 73mm، PDAF، OIS، 3x optical zoom",
    camera_macro: "50 MP، f/4.3، 135mm، PDAF، OIS، 6x optical zoom",
    camera_front: "32 MP، f/2.4، 21mm (عريضة)",
    camera_video: "4K@24/30/60fps، 1080p@30/60/240fps، HDR، Dolby Vision",
    audio_speakers: "ستيريو",
    audio_jack: "لا",
    connectivity_sim: "Dual SIM (Nano-SIM، dual stand-by)",
    connectivity_network: "5G",
    connectivity_wifi: "Wi-Fi 7",
    connectivity_bluetooth: "5.4",
    connectivity_nfc: "نعم",
    connectivity_gps: "GPS، GLONASS، GALILEO، QZSS، BDS، NavIC",
    protection_water: "IP68/IP69",
    protection_standard: "مقاوم للماء والغبار",
    battery_capacity: "5910 mAh",
    battery_charging: "80W سلكي، 100% في 46 دقيقة",
    battery_wireless: "50W لاسلكي",
    battery_reverse: "نعم (10W)",
    software_os: "Android 15",
    software_ui: "ColorOS 15",
    sensor_fingerprint: "نعم (تحت الشاشة، بصري)",
    sensor_face_unlock: "نعم",
    sensor_gyroscope: "نعم",
    sensor_compass: "نعم",
    sensor_proximity: "نعم",
    sensor_light: "نعم",
    sensor_other: "مقياس تسارع، مستشعر الأشعة تحت الحمراء",
    status: "published"
  },
  {
    brand: "Honor",
    name: "Magic 7 Pro",
    name_ar: "هونر ماجيك 7 برو",
    slug: "honor-magic-7-pro",
    year: 2025,
    release_date: "يناير 2025",
    image: "https://fdn2.gsmarena.com/vv/bigpic/honor-magic7-pro.jpg",
    quick_screen: '6.8" LTPO OLED 120Hz',
    quick_processor: "Snapdragon 8 Elite",
    quick_camera: "50 MP + 50 MP + 200 MP",
    quick_front_camera: "50 MP + TOF 3D",
    quick_memory: "256/512GB/1TB, 12/16GB RAM",
    quick_battery: "5850 mAh",
    design_height: "162.7 mm",
    design_width: "77.1 mm",
    design_thickness: "8.8 mm",
    design_weight: "223 g",
    design_materials: "زجاج أمامي وخلفي، إطار ألمنيوم",
    design_colors: "أسود، أبيض، أزرق، رمادي",
    design_frame: "ألمنيوم",
    screen_type: "LTPO OLED، 1.07B colors، 120Hz، HDR10+",
    screen_size: '6.8"',
    screen_resolution: "1280 x 2800 بكسل",
    screen_ppi: "453 ppi",
    screen_refresh_rate: "1-120Hz",
    screen_brightness: "5000 nits (peak)",
    screen_protection: "Honor NanoCrystal Shield",
    processor_name: "Snapdragon 8 Elite",
    processor_cores: "8 أنوية (2x4.32 GHz + 6x3.53 GHz)",
    processor_frequency: "4.32 GHz",
    processor_gpu: "Adreno 830",
    processor_fabrication: "3 nm",
    antutu_score: "2750000",
    memory_storage: "256GB، 512GB، 1TB",
    memory_ram: "12GB، 16GB",
    memory_type: "UFS 4.0",
    memory_sd_card: "لا",
    camera_main: "50 MP، f/1.4، 23mm (عريضة)، PDAF، Laser AF، OIS",
    camera_ultrawide: "50 MP، f/2.0، 12mm، 122°، PDAF",
    camera_telephoto: "200 MP، f/2.6، 68mm، PDAF، OIS، 3x optical zoom",
    camera_front: "50 MP، f/2.0، 22mm (عريضة) + TOF 3D",
    camera_video: "4K@24/30/60fps، 1080p@30/60/120/240fps، HDR",
    audio_speakers: "ستيريو",
    audio_jack: "لا",
    connectivity_sim: "Dual SIM (Nano-SIM، dual stand-by)",
    connectivity_network: "5G",
    connectivity_wifi: "Wi-Fi 7",
    connectivity_bluetooth: "5.4",
    connectivity_nfc: "نعم",
    connectivity_gps: "GPS، GLONASS، GALILEO، QZSS، BDS، NavIC",
    protection_water: "IP68/IP69",
    protection_standard: "مقاوم للماء والغبار",
    battery_capacity: "5850 mAh",
    battery_charging: "100W سلكي، 100% في 33 دقيقة",
    battery_wireless: "80W لاسلكي",
    battery_reverse: "نعم (10W)",
    software_os: "Android 15",
    software_ui: "MagicOS 9",
    sensor_fingerprint: "نعم (تحت الشاشة، بصري)",
    sensor_face_unlock: "نعم (3D)",
    sensor_gyroscope: "نعم",
    sensor_compass: "نعم",
    sensor_proximity: "نعم",
    sensor_light: "نعم",
    sensor_other: "مقياس تسارع، مستشعر الأشعة تحت الحمراء، باروميتر",
    status: "published"
  },
  {
    brand: "Huawei",
    name: "Mate 70 Pro",
    name_ar: "هواوي ميت 70 برو",
    slug: "huawei-mate-70-pro",
    year: 2025,
    release_date: "نوفمبر 2024",
    image: "https://fdn2.gsmarena.com/vv/bigpic/huawei-mate70-pro.jpg",
    quick_screen: '6.9" LTPO OLED 120Hz',
    quick_processor: "Kirin 9100 (7nm)",
    quick_camera: "50 MP + 40 MP + 48 MP",
    quick_front_camera: "13 MP + TOF 3D",
    quick_memory: "256/512GB/1TB, 12/16GB RAM",
    quick_battery: "5700 mAh",
    design_height: "163.7 mm",
    design_width: "79.0 mm",
    design_thickness: "8.8 mm",
    design_weight: "225 g",
    design_materials: "زجاج Kunlun Glass 2، إطار ألمنيوم",
    design_colors: "أسود، أبيض، ذهبي، أخضر",
    design_frame: "ألمنيوم",
    screen_type: "LTPO OLED، 1.07B colors، 120Hz، HDR",
    screen_size: '6.9"',
    screen_resolution: "1260 x 2832 بكسل",
    screen_ppi: "460 ppi",
    screen_refresh_rate: "1-120Hz",
    screen_brightness: "2500 nits (peak)",
    screen_protection: "Kunlun Glass 2",
    processor_name: "Kirin 9100",
    processor_cores: "12 أنوية (2x2.67 GHz + 6x2.32 GHz + 4x1.95 GHz)",
    processor_frequency: "2.67 GHz",
    processor_gpu: "Maleoon 920",
    processor_fabrication: "7 nm",
    antutu_score: "1500000",
    memory_storage: "256GB، 512GB، 1TB",
    memory_ram: "12GB، 16GB",
    memory_type: "UFS 3.1",
    memory_sd_card: "نعم (NM Card)",
    camera_main: "50 MP، f/1.4، 24mm (عريضة)، PDAF، Laser AF، OIS",
    camera_ultrawide: "40 MP، f/2.2، 13mm، 120°، PDAF",
    camera_telephoto: "48 MP، f/3.0، 90mm، PDAF، OIS، 3.5x optical zoom",
    camera_front: "13 MP، f/2.4، (ultrawide) + TOF 3D",
    camera_video: "4K@30/60fps، 1080p@30/60/240fps، HDR",
    audio_speakers: "ستيريو",
    audio_jack: "لا",
    connectivity_sim: "Dual SIM (Nano-SIM، dual stand-by)",
    connectivity_network: "5G",
    connectivity_wifi: "Wi-Fi 6",
    connectivity_bluetooth: "5.2",
    connectivity_nfc: "نعم",
    connectivity_gps: "GPS، GLONASS، GALILEO، QZSS، BDS، NavIC",
    protection_water: "IP68",
    protection_standard: "مقاوم للماء والغبار",
    battery_capacity: "5700 mAh",
    battery_charging: "100W سلكي، 80W لاسلكي، 20W عكسي",
    battery_wireless: "80W لاسلكي",
    battery_reverse: "نعم (20W)",
    software_os: "HarmonyOS 4.3",
    software_ui: "HarmonyOS 4.3",
    sensor_fingerprint: "نعم (تحت الشاشة، بصري)",
    sensor_face_unlock: "نعم (3D)",
    sensor_gyroscope: "نعم",
    sensor_compass: "نعم",
    sensor_proximity: "نعم",
    sensor_light: "نعم",
    sensor_other: "مقياس تسارع، مستشعر الأشعة تحت الحمراء، باروميتر، مقياس حرارة",
    status: "published"
  }
];

async function seedDatabase() {
  console.log("=== Starting Complete Database Seeding ===\n");

  console.log("Step 1: Ensuring all brands exist...");
  for (const brand of brandsList) {
    try {
      const existing = await db.query.brands.findFirst({
        where: eq(brands.slug, brand.slug)
      });

      if (!existing) {
        await db.insert(brands).values(brand);
        console.log(`  ✓ Added brand: ${brand.name}`);
      } else {
        console.log(`  • Brand exists: ${brand.name}`);
      }
    } catch (error: any) {
      console.log(`  ❌ Error with brand ${brand.name}: ${error.message}`);
    }
  }

  console.log("\nStep 2: Adding phones to database...");
  let successCount = 0;
  let updateCount = 0;
  let failCount = 0;

  for (const phoneData of phones2025) {
    try {
      console.log(`\nProcessing: ${phoneData.name}...`);

      const brandData = await db.query.brands.findFirst({
        where: eq(brands.name, phoneData.brand)
      });

      if (!brandData) {
        console.log(`  ❌ Brand '${phoneData.brand}' not found`);
        failCount++;
        continue;
      }

      const { brand, ...phonePayload } = phoneData as any;
      phonePayload.brand_id = brandData.id;

      const existingPhone = await db.query.phones.findFirst({
        where: eq(phones.slug, phoneData.slug)
      });

      if (existingPhone) {
        await db.update(phones)
          .set(phonePayload)
          .where(eq(phones.id, existingPhone.id));
        console.log(`  ✓ Updated successfully`);
        updateCount++;
      } else {
        await db.insert(phones).values(phonePayload);
        console.log(`  ✓ Inserted successfully`);
        successCount++;
      }
    } catch (error: any) {
      console.log(`  ❌ Error: ${error.message}`);
      failCount++;
    }
  }

  console.log("\n=== Seeding Complete ===");
  console.log(`New phones added: ${successCount}`);
  console.log(`Phones updated: ${updateCount}`);
  console.log(`Failed: ${failCount}`);
}

seedDatabase().catch(console.error).finally(() => process.exit(0));
