import "dotenv/config";
import { createClient } from "@supabase/supabase-js";

const supabaseUrl = process.env.VITE_SUPABASE_URL!;
const supabaseKey = process.env.VITE_SUPABASE_PUBLISHABLE_KEY!;

if (!supabaseUrl || !supabaseKey) {
  throw new Error("Missing Supabase credentials");
}

const supabase = createClient(supabaseUrl, supabaseKey);

const phones2025_2026 = [
  // Samsung Galaxy S25 Ultra
  {
    slug: "samsung-galaxy-s25-ultra",
    name: "Samsung Galaxy S25 Ultra",
    name_ar: "سامسونج جالاكسي S25 ألترا",
    brand: "Samsung",
    year: 2025,
    release_date: "يناير 2025",
    image: "https://fdn2.gsmarena.com/vv/bigpic/samsung-galaxy-s25-ultra.jpg",
    status: "published",
    quick_screen: "6.9 بوصة Dynamic AMOLED 2X، 120Hz",
    quick_processor: "Snapdragon 8 Elite",
    quick_camera: "200 ميجابكسل رئيسية",
    quick_front_camera: "12 ميجابكسل",
    quick_memory: "256/512GB/1TB مع 12GB رام",
    quick_battery: "5000 مللي أمبير، شحن 45 واط",
    design_height: "162.8 ملم",
    design_width: "77.6 ملم",
    design_thickness: "8.2 ملم",
    design_weight: "218 جرام",
    design_materials: "زجاج Gorilla Armor 2، إطار من التيتانيوم",
    design_colors: "أسود تيتانيوم، رمادي تيتانيوم، فضي تيتانيوم، أزرق تيتانيوم",
    design_frame: "إطار من التيتانيوم",
    screen_type: "Dynamic AMOLED 2X",
    screen_size: "6.9 بوصة",
    screen_resolution: "1440 × 3120 بكسل",
    screen_ppi: "505 بكسل لكل بوصة",
    screen_refresh_rate: "120Hz",
    screen_touch_rate: "240Hz",
    screen_brightness: "2600 نيت",
    screen_protection: "Corning Gorilla Armor 2",
    screen_back_protection: "Gorilla Glass Victus 2",
    processor_name: "Qualcomm Snapdragon 8 Elite (3nm)",
    processor_cores: "ثماني النواة",
    processor_frequency: "1×4.32 GHz + 3×3.53 GHz + 4×2.75 GHz",
    processor_gpu: "Adreno 830",
    processor_fabrication: "3 نانومتر",
    antutu_score: "2,850,000",
    memory_storage: "256/512GB/1TB",
    memory_ram: "12GB",
    memory_type: "UFS 4.0",
    memory_sd_card: "لا",
    camera_main: "200 ميجابكسل، f/1.7، OIS، PDAF متعدد الاتجاهات",
    camera_ultrawide: "50 ميجابكسل، f/1.9، زاوية فائقة الاتساع 120°",
    camera_telephoto: "50 ميجابكسل، f/3.4، تقريب بصري 5× + 10 ميجابكسل، f/2.4، تقريب بصري 3×",
    camera_macro: "دمج في الكاميرا الرئيسية",
    camera_front: "12 ميجابكسل، f/2.2",
    camera_video: "8K@30fps، 4K@60fps مع HDR10+، Super Steady",
    audio_speakers: "ستيريو من AKG",
    audio_jack: "لا",
    connectivity_sim: "Nano-SIM + eSIM",
    connectivity_network: "5G SA/NSA، 4G LTE",
    connectivity_wifi: "Wi-Fi 7 (802.11be)",
    connectivity_bluetooth: "5.4",
    connectivity_nfc: "نعم",
    connectivity_gps: "GPS، Galileo، GLONASS، BeiDou، QZSS",
    protection_water: "IP68",
    protection_standard: "IP68 (مقاومة الماء حتى 1.5 متر لمدة 30 دقيقة)",
    battery_capacity: "5000 مللي أمبير",
    battery_charging: "45 واط سلكي، PD 3.0",
    battery_wireless: "15 واط لاسلكي",
    battery_reverse: "4.5 واط عكسي لاسلكي",
    software_os: "Android 15",
    software_ui: "One UI 7",
    sensor_fingerprint: "بالموجات فوق الصوتية تحت الشاشة",
    sensor_face_unlock: "نعم",
    sensor_gyroscope: "نعم",
    sensor_compass: "نعم",
    sensor_proximity: "نعم",
    sensor_light: "نعم",
    sensor_other: "مقياس التسارع، البارومتر، Hall، S Pen"
  },

  // Samsung Galaxy S25+
  {
    slug: "samsung-galaxy-s25-plus",
    name: "Samsung Galaxy S25+",
    name_ar: "سامسونج جالاكسي S25 بلس",
    brand: "Samsung",
    year: 2025,
    release_date: "يناير 2025",
    image: "https://fdn2.gsmarena.com/vv/bigpic/samsung-galaxy-s25-plus.jpg",
    status: "published",
    quick_screen: "6.7 بوصة Dynamic AMOLED 2X، 120Hz",
    quick_processor: "Snapdragon 8 Elite",
    quick_camera: "50 ميجابكسل رئيسية",
    quick_front_camera: "12 ميجابكسل",
    quick_memory: "256/512GB مع 12GB رام",
    quick_battery: "4900 مللي أمبير، شحن 45 واط",
    design_height: "158.9 ملم",
    design_width: "75.8 ملم",
    design_thickness: "7.3 ملم",
    design_weight: "190 جرام",
    design_materials: "زجاج Gorilla Glass Victus 2، إطار ألمنيوم",
    design_colors: "أزرق جليدي، أسود، فضي، بنفسجي",
    design_frame: "إطار ألمنيوم",
    screen_type: "Dynamic AMOLED 2X",
    screen_size: "6.7 بوصة",
    screen_resolution: "1440 × 3120 بكسل",
    screen_ppi: "513 بكسل لكل بوصة",
    screen_refresh_rate: "120Hz",
    screen_brightness: "2600 نيت",
    screen_protection: "Corning Gorilla Glass Victus 2",
    processor_name: "Qualcomm Snapdragon 8 Elite (3nm)",
    processor_cores: "ثماني النواة",
    processor_frequency: "1×4.32 GHz + 3×3.53 GHz + 4×2.75 GHz",
    processor_gpu: "Adreno 830",
    processor_fabrication: "3 نانومتر",
    antutu_score: "2,850,000",
    memory_storage: "256/512GB",
    memory_ram: "12GB",
    memory_type: "UFS 4.0",
    memory_sd_card: "لا",
    camera_main: "50 ميجابكسل، f/1.8، OIS، Dual Pixel PDAF",
    camera_ultrawide: "12 ميجابكسل، f/2.2، زاوية واسعة 120°",
    camera_telephoto: "10 ميجابكسل، f/2.4، تقريب بصري 3×، OIS",
    camera_front: "12 ميجابكسل، f/2.2",
    camera_video: "8K@30fps، 4K@60fps",
    audio_speakers: "ستيريو من AKG",
    audio_jack: "لا",
    connectivity_sim: "Nano-SIM + eSIM",
    connectivity_network: "5G SA/NSA",
    connectivity_wifi: "Wi-Fi 7",
    connectivity_bluetooth: "5.4",
    connectivity_nfc: "نعم",
    connectivity_gps: "نعم",
    protection_water: "IP68",
    protection_standard: "IP68",
    battery_capacity: "4900 مللي أمبير",
    battery_charging: "45 واط",
    battery_wireless: "15 واط",
    battery_reverse: "4.5 واط",
    software_os: "Android 15",
    software_ui: "One UI 7",
    sensor_fingerprint: "بالموجات فوق الصوتية تحت الشاشة",
    sensor_face_unlock: "نعم",
    sensor_gyroscope: "نعم",
    sensor_compass: "نعم",
    sensor_proximity: "نعم",
    sensor_light: "نعم",
    sensor_other: "مقياس التسارع، البارومتر"
  },

  // iPhone 17 Pro Max
  {
    slug: "apple-iphone-17-pro-max",
    name: "Apple iPhone 17 Pro Max",
    name_ar: "آبل آيفون 17 برو ماكس",
    brand: "Apple",
    year: 2025,
    release_date: "سبتمبر 2025",
    image: "https://fdn2.gsmarena.com/vv/bigpic/apple-iphone-16-pro-max.jpg",
    status: "published",
    quick_screen: "6.9 بوصة Super Retina XDR، 120Hz",
    quick_processor: "Apple A19 Pro",
    quick_camera: "48 ميجابكسل رئيسية",
    quick_front_camera: "12 ميجابكسل",
    quick_memory: "256/512GB/1TB مع 12GB رام",
    quick_battery: "4685 مللي أمبير، شحن 45 واط",
    design_height: "163.0 ملم",
    design_width: "77.6 ملم",
    design_thickness: "8.25 ملم",
    design_weight: "225 جرام",
    design_materials: "زجاج خلفي محكم، إطار من التيتانيوم",
    design_colors: "تيتانيوم طبيعي، تيتانيوم أبيض، تيتانيوم أسود، تيتانيوم صحراوي",
    design_frame: "إطار من التيتانيوم من الدرجة 5",
    screen_type: "Super Retina XDR OLED، LTPO",
    screen_size: "6.9 بوصة",
    screen_resolution: "1320 × 2868 بكسل",
    screen_ppi: "460 بكسل لكل بوصة",
    screen_refresh_rate: "1-120Hz (ProMotion)",
    screen_brightness: "2000 نيت (HDR)، 1000 نيت (عادي)",
    screen_protection: "Ceramic Shield",
    processor_name: "Apple A19 Pro (3nm)",
    processor_cores: "سداسي النواة",
    processor_frequency: "2×4.05 GHz + 4×2.42 GHz",
    processor_gpu: "Apple GPU (8 أنوية)",
    processor_fabrication: "3 نانومتر",
    antutu_score: "2,900,000",
    memory_storage: "256/512GB/1TB",
    memory_ram: "12GB",
    memory_type: "NVMe",
    memory_sd_card: "لا",
    camera_main: "48 ميجابكسل، f/1.78، OIS، Sensor-shift",
    camera_ultrawide: "48 ميجابكسل، f/2.2، زاوية واسعة 120°",
    camera_telephoto: "12 ميجابكسل، f/2.8، تقريب بصري 5×، OIS",
    camera_front: "12 ميجابكسل، f/1.9، autofocus",
    camera_video: "4K@120fps، ProRes، Cinematic mode 4K@60fps",
    audio_speakers: "ستيريو",
    audio_jack: "لا",
    connectivity_sim: "نانو سيم + eSIM (دعم ثنائي eSIM)",
    connectivity_network: "5G SA/NSA",
    connectivity_wifi: "Wi-Fi 7 (802.11be)",
    connectivity_bluetooth: "5.4",
    connectivity_nfc: "نعم",
    connectivity_gps: "GPS، GLONASS، Galileo، QZSS، BeiDou",
    protection_water: "IP68",
    protection_standard: "IP68 (حتى 6 أمتار لمدة 30 دقيقة)",
    battery_capacity: "4685 مللي أمبير",
    battery_charging: "45 واط سلكي (USB-C)، MagSafe 25 واط",
    battery_wireless: "25 واط MagSafe",
    battery_reverse: "لا",
    software_os: "iOS 19",
    software_ui: "iOS 19",
    sensor_fingerprint: "لا",
    sensor_face_unlock: "Face ID (3D)",
    sensor_gyroscope: "نعم",
    sensor_compass: "نعم",
    sensor_proximity: "نعم",
    sensor_light: "نعم",
    sensor_other: "مقياس التسارع، البارومتر، LiDAR Scanner، Ultra Wideband (UWB)"
  },

  // Google Pixel 10 Pro
  {
    slug: "google-pixel-10-pro",
    name: "Google Pixel 10 Pro",
    name_ar: "جوجل بيكسل 10 برو",
    brand: "Google",
    year: 2025,
    release_date: "أكتوبر 2025",
    image: "https://fdn2.gsmarena.com/vv/bigpic/google-pixel-9-pro-xl.jpg",
    status: "published",
    quick_screen: "6.8 بوصة LTPO OLED، 120Hz",
    quick_processor: "Google Tensor G5",
    quick_camera: "50 ميجابكسل رئيسية",
    quick_front_camera: "42 ميجابكسل",
    quick_memory: "256/512GB/1TB مع 16GB رام",
    quick_battery: "5050 مللي أمبير، شحن 45 واط",
    design_height: "162.8 ملم",
    design_width: "76.6 ملم",
    design_thickness: "8.5 ملم",
    design_weight: "221 جرام",
    design_materials: "زجاج Gorilla Glass Victus 3، إطار ألمنيوم",
    design_colors: "أسود سبجي، أبيض بورسلين، رمادي خليجي",
    design_frame: "إطار ألمنيوم معاد تدويره",
    screen_type: "LTPO OLED",
    screen_size: "6.8 بوصة",
    screen_resolution: "1344 × 2992 بكسل",
    screen_ppi: "486 بكسل لكل بوصة",
    screen_refresh_rate: "1-120Hz",
    screen_brightness: "3000 نيت (ذروة)",
    screen_protection: "Corning Gorilla Glass Victus 3",
    processor_name: "Google Tensor G5 (3nm)",
    processor_cores: "ثماني النواة",
    processor_frequency: "1×3.4 GHz + 3×3.0 GHz + 4×2.1 GHz",
    processor_gpu: "Immortalis-G925 MC12",
    processor_fabrication: "3 نانومتر",
    antutu_score: "1,850,000",
    memory_storage: "256/512GB/1TB",
    memory_ram: "16GB",
    memory_type: "UFS 4.0",
    memory_sd_card: "لا",
    camera_main: "50 ميجابكسل، f/1.68، OIS، LDAF، PDAF",
    camera_ultrawide: "50 ميجابكسل، f/1.95، زاوية واسعة 123°",
    camera_telephoto: "48 ميجابكسل، f/2.8، تقريب بصري 5×، OIS",
    camera_front: "42 ميجابكسل، f/2.2، autofocus",
    camera_video: "8K@30fps، 4K@60fps، Night Sight Video",
    audio_speakers: "ستيريو",
    audio_jack: "لا",
    connectivity_sim: "نانو سيم + eSIM",
    connectivity_network: "5G SA/NSA",
    connectivity_wifi: "Wi-Fi 7",
    connectivity_bluetooth: "5.4",
    connectivity_nfc: "نعم",
    connectivity_gps: "GPS، GLONASS، Galileo، QZSS، BeiDou، NavIC",
    protection_water: "IP68",
    protection_standard: "IP68",
    battery_capacity: "5050 مللي أمبير",
    battery_charging: "45 واط سلكي، PD 3.0",
    battery_wireless: "23 واط لاسلكي",
    battery_reverse: "12 واط عكسي",
    software_os: "Android 16",
    software_ui: "Pixel UI",
    sensor_fingerprint: "بصري تحت الشاشة",
    sensor_face_unlock: "نعم",
    sensor_gyroscope: "نعم",
    sensor_compass: "نعم",
    sensor_proximity: "نعم",
    sensor_light: "نعم",
    sensor_other: "مقياس التسارع، البارومتر، مقياس الحرارة"
  },

  // Xiaomi 15 Ultra
  {
    slug: "xiaomi-15-ultra",
    name: "Xiaomi 15 Ultra",
    name_ar: "شاومي 15 ألترا",
    brand: "Xiaomi",
    year: 2025,
    release_date: "فبراير 2025",
    image: "https://fdn2.gsmarena.com/vv/bigpic/xiaomi-14-ultra.jpg",
    status: "published",
    quick_screen: "6.73 بوصة LTPO AMOLED، 120Hz",
    quick_processor: "Snapdragon 8 Elite",
    quick_camera: "50 ميجابكسل رئيسية، عدسات Leica",
    quick_front_camera: "32 ميجابكسل",
    quick_memory: "256/512GB/1TB مع 16GB رام",
    quick_battery: "5300 مللي أمبير، شحن 90 واط",
    design_height: "161.4 ملم",
    design_width: "75.3 ملم",
    design_thickness: "9.2 ملم",
    design_weight: "229 جرام",
    design_materials: "زجاج Gorilla Glass Victus 2، إطار ألمنيوم",
    design_colors: "أسود، أبيض، أزرق",
    design_frame: "إطار ألمنيوم",
    screen_type: "LTPO AMOLED",
    screen_size: "6.73 بوصة",
    screen_resolution: "1440 × 3200 بكسل",
    screen_ppi: "522 بكسل لكل بوصة",
    screen_refresh_rate: "1-120Hz",
    screen_brightness: "3000 نيت (ذروة)",
    screen_protection: "Corning Gorilla Glass Victus 2",
    processor_name: "Qualcomm Snapdragon 8 Elite (3nm)",
    processor_cores: "ثماني النواة",
    processor_frequency: "1×4.32 GHz + 3×3.53 GHz + 4×2.75 GHz",
    processor_gpu: "Adreno 830",
    processor_fabrication: "3 نانومتر",
    antutu_score: "2,850,000",
    memory_storage: "256/512GB/1TB",
    memory_ram: "16GB",
    memory_type: "UFS 4.0",
    memory_sd_card: "لا",
    camera_main: "50 ميجابكسل، f/1.6، OIS، عدسات Leica Summilux، مستشعر LYT-900",
    camera_ultrawide: "50 ميجابكسل، f/1.8، زاوية واسعة 122°",
    camera_telephoto: "50 ميجابكسل، f/1.8، تقريب بصري 3.2× + 50 ميجابكسل، f/2.5، تقريب بصري 5×",
    camera_front: "32 ميجابكسل، f/2.0",
    camera_video: "8K@30fps، 4K@60fps، Dolby Vision HDR",
    audio_speakers: "رباعي بواسطة Harman Kardon",
    audio_jack: "لا",
    connectivity_sim: "Dual Nano-SIM",
    connectivity_network: "5G SA/NSA",
    connectivity_wifi: "Wi-Fi 7",
    connectivity_bluetooth: "5.4",
    connectivity_nfc: "نعم",
    connectivity_gps: "GPS، GLONASS، Galileo، BeiDou، QZSS، NavIC",
    protection_water: "IP68",
    protection_standard: "IP68",
    battery_capacity: "5300 مللي أمبير",
    battery_charging: "90 واط سلكي، 80 واط لاسلكي",
    battery_wireless: "80 واط",
    battery_reverse: "10 واط",
    software_os: "Android 15",
    software_ui: "HyperOS 2.0",
    sensor_fingerprint: "بالموجات فوق الصوتية تحت الشاشة",
    sensor_face_unlock: "نعم",
    sensor_gyroscope: "نعم",
    sensor_compass: "نعم",
    sensor_proximity: "نعم",
    sensor_light: "نعم",
    sensor_other: "مقياس التسارع، البارومتر، مستشعر الأشعة تحت الحمراء"
  },

  // OnePlus 13 Pro
  {
    slug: "oneplus-13-pro",
    name: "OnePlus 13 Pro",
    name_ar: "ون بلس 13 برو",
    brand: "OnePlus",
    year: 2025,
    release_date: "يناير 2025",
    image: "https://fdn2.gsmarena.com/vv/bigpic/oneplus-12.jpg",
    status: "published",
    quick_screen: "6.82 بوصة LTPO AMOLED، 120Hz",
    quick_processor: "Snapdragon 8 Elite",
    quick_camera: "50 ميجابكسل رئيسية، عدسات Hasselblad",
    quick_front_camera: "32 ميجابكسل",
    quick_memory: "256/512GB مع 12/16GB رام",
    quick_battery: "5400 مللي أمبير، شحن 100 واط",
    design_height: "162.9 ملم",
    design_width: "76.5 ملم",
    design_thickness: "8.9 ملم",
    design_weight: "210 جرام",
    design_materials: "زجاج Gorilla Glass Victus 2، إطار ألمنيوم",
    design_colors: "أخضر صنوبري، أسود قمري، أبيض رخامي",
    design_frame: "إطار ألمنيوم",
    screen_type: "LTPO AMOLED",
    screen_size: "6.82 بوصة",
    screen_resolution: "1440 × 3168 بكسل",
    screen_ppi: "510 بكسل لكل بوصة",
    screen_refresh_rate: "1-120Hz",
    screen_brightness: "4500 نيت (ذروة)",
    screen_protection: "Corning Gorilla Glass Victus 2",
    processor_name: "Qualcomm Snapdragon 8 Elite (3nm)",
    processor_cores: "ثماني النواة",
    processor_gpu: "Adreno 830",
    processor_fabrication: "3 نانومتر",
    antutu_score: "2,850,000",
    memory_storage: "256/512GB",
    memory_ram: "12/16GB",
    memory_type: "UFS 4.0",
    memory_sd_card: "لا",
    camera_main: "50 ميجابكسل، f/1.6، OIS، عدسات Hasselblad",
    camera_ultrawide: "50 ميجابكسل، f/2.0، زاوية واسعة 114°",
    camera_telephoto: "64 ميجابكسل، f/2.6، تقريب بصري 3×، OIS",
    camera_front: "32 ميجابكسل، f/2.4",
    camera_video: "8K@30fps، 4K@60fps، HDR",
    audio_speakers: "ستيريو",
    audio_jack: "لا",
    connectivity_sim: "Dual Nano-SIM",
    connectivity_network: "5G SA/NSA",
    connectivity_wifi: "Wi-Fi 7",
    connectivity_bluetooth: "5.4",
    connectivity_nfc: "نعم",
    connectivity_gps: "GPS، GLONASS، Galileo، BeiDou، QZSS",
    protection_water: "IP68",
    protection_standard: "IP68",
    battery_capacity: "5400 مللي أمبير",
    battery_charging: "100 واط SuperVOOC",
    battery_wireless: "50 واط AIRVOOC",
    battery_reverse: "10 واط",
    software_os: "Android 15",
    software_ui: "OxygenOS 15",
    sensor_fingerprint: "بصري تحت الشاشة",
    sensor_face_unlock: "نعم",
    sensor_gyroscope: "نعم",
    sensor_compass: "نعم",
    sensor_proximity: "نعم",
    sensor_light: "نعم",
    sensor_other: "مقياس التسارع، البارومتر، مستشعر الأشعة تحت الحمراء"
  },

  // Oppo Find X8 Pro
  {
    slug: "oppo-find-x8-pro",
    name: "Oppo Find X8 Pro",
    name_ar: "أوبو فايند X8 برو",
    brand: "Oppo",
    year: 2025,
    release_date: "فبراير 2025",
    image: "https://fdn2.gsmarena.com/vv/bigpic/oppo-find-x7-ultra.jpg",
    status: "published",
    quick_screen: "6.78 بوصة LTPO AMOLED، 120Hz",
    quick_processor: "Snapdragon 8 Elite",
    quick_camera: "50 ميجابكسل رئيسية، عدسات Hasselblad",
    quick_front_camera: "32 ميجابكسل",
    quick_memory: "256/512GB مع 12/16GB رام",
    quick_battery: "5000 مللي أمبير، شحن 100 واط",
    design_height: "162.3 ملم",
    design_width: "76.7 ملم",
    design_thickness: "8.4 ملم",
    design_weight: "215 جرام",
    design_materials: "زجاج Gorilla Glass Victus 2، إطار ألمنيوم",
    design_colors: "أسود، بني، أخضر",
    design_frame: "إطار ألمنيوم",
    screen_type: "LTPO AMOLED",
    screen_size: "6.78 بوصة",
    screen_resolution: "1440 × 3168 بكسل",
    screen_ppi: "510 بكسل لكل بوصة",
    screen_refresh_rate: "1-120Hz",
    screen_brightness: "4500 نيت (ذروة)",
    screen_protection: "Corning Gorilla Glass Victus 2",
    processor_name: "Qualcomm Snapdragon 8 Elite (3nm)",
    processor_cores: "ثماني النواة",
    processor_gpu: "Adreno 830",
    processor_fabrication: "3 نانومتر",
    antutu_score: "2,850,000",
    memory_storage: "256/512GB",
    memory_ram: "12/16GB",
    memory_type: "UFS 4.0",
    memory_sd_card: "لا",
    camera_main: "50 ميجابكسل، f/1.8، OIS، عدسات Hasselblad",
    camera_ultrawide: "50 ميجابكسل، f/2.0، زاوية واسعة 114°",
    camera_telephoto: "50 ميجابكسل، f/2.6، تقريب بصري 3× + 50 ميجابكسل، f/4.3، تقريب بصري 6×",
    camera_front: "32 ميجابكسل، f/2.4",
    camera_video: "4K@60fps، Dolby Vision HDR",
    audio_speakers: "ستيريو",
    audio_jack: "لا",
    connectivity_sim: "Dual Nano-SIM",
    connectivity_network: "5G SA/NSA",
    connectivity_wifi: "Wi-Fi 7",
    connectivity_bluetooth: "5.4",
    connectivity_nfc: "نعم",
    connectivity_gps: "GPS، GLONASS، Galileo، BeiDou، QZSS",
    protection_water: "IP68",
    protection_standard: "IP68",
    battery_capacity: "5000 مللي أمبير",
    battery_charging: "100 واط SuperVOOC",
    battery_wireless: "50 واط AIRVOOC",
    battery_reverse: "10 واط",
    software_os: "Android 15",
    software_ui: "ColorOS 15",
    sensor_fingerprint: "بصري تحت الشاشة",
    sensor_face_unlock: "نعم",
    sensor_gyroscope: "نعم",
    sensor_compass: "نعم",
    sensor_proximity: "نعم",
    sensor_light: "نعم",
    sensor_other: "مقياس التسارع، البارومتر"
  },

  // Vivo X200 Pro
  {
    slug: "vivo-x200-pro",
    name: "Vivo X200 Pro",
    name_ar: "فيفو X200 برو",
    brand: "Vivo",
    year: 2025,
    release_date: "يناير 2025",
    image: "https://fdn2.gsmarena.com/vv/bigpic/vivo-x100-pro.jpg",
    status: "published",
    quick_screen: "6.78 بوصة LTPO AMOLED، 120Hz",
    quick_processor: "MediaTek Dimensity 9400",
    quick_camera: "50 ميجابكسل رئيسية، عدسات Zeiss",
    quick_front_camera: "32 ميجابكسل",
    quick_memory: "256/512GB مع 12/16GB رام",
    quick_battery: "5400 مللي أمبير، شحن 100 واط",
    design_height: "164.1 ملم",
    design_width: "75.3 ملم",
    design_thickness: "8.9 ملم",
    design_weight: "221 جرام",
    design_materials: "زجاج Gorilla Glass Victus 2، إطار ألمنيوم",
    design_colors: "أسود، أبيض، أزرق",
    design_frame: "إطار ألمنيوم",
    screen_type: "LTPO AMOLED",
    screen_size: "6.78 بوصة",
    screen_resolution: "1440 × 3200 بكسل",
    screen_ppi: "517 بكسل لكل بوصة",
    screen_refresh_rate: "1-120Hz",
    screen_brightness: "3000 نيت (ذروة)",
    screen_protection: "Corning Gorilla Glass Victus 2",
    processor_name: "MediaTek Dimensity 9400 (3nm)",
    processor_cores: "ثماني النواة",
    processor_gpu: "Immortalis-G925 MC12",
    processor_fabrication: "3 نانومتر",
    antutu_score: "2,700,000",
    memory_storage: "256/512GB",
    memory_ram: "12/16GB",
    memory_type: "UFS 4.0",
    memory_sd_card: "لا",
    camera_main: "50 ميجابكسل، f/1.57، OIS، عدسات Zeiss",
    camera_ultrawide: "50 ميجابكسل، f/2.0، زاوية واسعة 116°",
    camera_telephoto: "50 ميجابكسل، f/2.5، تقريب بصري 3.7×، OIS + 200 ميجابكسل، f/2.67، تقريب بصري 4.3×",
    camera_front: "32 ميجابكسل، f/2.0",
    camera_video: "8K@30fps، 4K@60fps، Dolby Vision",
    audio_speakers: "ستيريو",
    audio_jack: "لا",
    connectivity_sim: "Dual Nano-SIM",
    connectivity_network: "5G SA/NSA",
    connectivity_wifi: "Wi-Fi 7",
    connectivity_bluetooth: "5.4",
    connectivity_nfc: "نعم",
    connectivity_gps: "GPS، GLONASS، Galileo، BeiDou، QZSS",
    protection_water: "IP68",
    protection_standard: "IP68",
    battery_capacity: "5400 مللي أمبير",
    battery_charging: "100 واط FlashCharge",
    battery_wireless: "50 واط لاسلكي",
    battery_reverse: "10 واط",
    software_os: "Android 15",
    software_ui: "OriginOS 5 / Funtouch OS 15",
    sensor_fingerprint: "بالموجات فوق الصوتية تحت الشاشة",
    sensor_face_unlock: "نعم",
    sensor_gyroscope: "نعم",
    sensor_compass: "نعم",
    sensor_proximity: "نعم",
    sensor_light: "نعم",
    sensor_other: "مقياس التسارع، البارومتر، مستشعر الأشعة تحت الحمراء"
  },

  // Honor Magic 7 Pro
  {
    slug: "honor-magic-7-pro",
    name: "Honor Magic 7 Pro",
    name_ar: "هونر ماجيك 7 برو",
    brand: "Honor",
    year: 2025,
    release_date: "يناير 2025",
    image: "https://fdn2.gsmarena.com/vv/bigpic/honor-magic6-pro.jpg",
    status: "published",
    quick_screen: "6.8 بوصة LTPO OLED، 120Hz",
    quick_processor: "Snapdragon 8 Elite",
    quick_camera: "50 ميجابكسل رئيسية",
    quick_front_camera: "50 ميجابكسل",
    quick_memory: "256/512GB/1TB مع 12/16GB رام",
    quick_battery: "5850 مللي أمبير، شحن 100 واط",
    design_height: "162.8 ملم",
    design_width: "77.1 ملم",
    design_thickness: "8.8 ملم",
    design_weight: "223 جرام",
    design_materials: "زجاج خلفي، إطار ألمنيوم",
    design_colors: "أسود، أبيض، أخضر",
    design_frame: "إطار ألمنيوم",
    screen_type: "LTPO OLED",
    screen_size: "6.8 بوصة",
    screen_resolution: "1280 × 2800 بكسل",
    screen_ppi: "453 بكسل لكل بوصة",
    screen_refresh_rate: "1-120Hz",
    screen_brightness: "5000 نيت (ذروة)",
    screen_protection: "NanoCrystal Shield",
    processor_name: "Qualcomm Snapdragon 8 Elite (3nm)",
    processor_cores: "ثماني النواة",
    processor_gpu: "Adreno 830",
    processor_fabrication: "3 نانومتر",
    antutu_score: "2,850,000",
    memory_storage: "256/512GB/1TB",
    memory_ram: "12/16GB",
    memory_type: "UFS 4.0",
    memory_sd_card: "لا",
    camera_main: "50 ميجابكسل، f/1.4-f/2.0، OIS، Variable Aperture",
    camera_ultrawide: "50 ميجابكسل، f/2.0، زاوية واسعة 122°",
    camera_telephoto: "200 ميجابكسل، f/2.6، تقريب بصري 3×، OIS",
    camera_front: "50 ميجابكسل، f/2.0، 3D ToF",
    camera_video: "4K@60fps، Dolby Vision HDR",
    audio_speakers: "ستيريو",
    audio_jack: "لا",
    connectivity_sim: "Dual Nano-SIM",
    connectivity_network: "5G SA/NSA",
    connectivity_wifi: "Wi-Fi 7",
    connectivity_bluetooth: "5.4",
    connectivity_nfc: "نعم",
    connectivity_gps: "GPS، GLONASS، Galileo، BeiDou، QZSS",
    protection_water: "IP68/IP69",
    protection_standard: "IP68/IP69",
    battery_capacity: "5850 مللي أمبير",
    battery_charging: "100 واط SuperCharge",
    battery_wireless: "80 واط لاسلكي",
    battery_reverse: "5 واط",
    software_os: "Android 15",
    software_ui: "MagicOS 9.0",
    sensor_fingerprint: "بالموجات فوق الصوتية تحت الشاشة",
    sensor_face_unlock: "3D Face Recognition",
    sensor_gyroscope: "نعم",
    sensor_compass: "نعم",
    sensor_proximity: "نعم",
    sensor_light: "نعم",
    sensor_other: "مقياس التسارع، البارومتر، مستشعر الأشعة تحت الحمراء"
  },

  // Huawei Mate 70 Pro
  {
    slug: "huawei-mate-70-pro",
    name: "Huawei Mate 70 Pro",
    name_ar: "هواوي ميت 70 برو",
    brand: "Huawei",
    year: 2025,
    release_date: "مارس 2025",
    image: "https://fdn2.gsmarena.com/vv/bigpic/huawei-mate60-pro-plus.jpg",
    status: "published",
    quick_screen: "6.88 بوصة LTPO OLED، 120Hz",
    quick_processor: "Kirin 9100",
    quick_camera: "50 ميجابكسل رئيسية، عدسات Leica",
    quick_front_camera: "13 ميجابكسل + 3D ToF",
    quick_memory: "256/512GB/1TB مع 12/16GB رام",
    quick_battery: "5500 مللي أمبير، شحن 100 واط",
    design_height: "163.7 ملم",
    design_width: "79.0 ملم",
    design_thickness: "8.5 ملم",
    design_weight: "225 جرام",
    design_materials: "زجاج Kunlun، إطار ألمنيوم",
    design_colors: "أسود، أبيض، ذهبي، أخضر",
    design_frame: "إطار ألمنيوم",
    screen_type: "LTPO OLED",
    screen_size: "6.88 بوصة",
    screen_resolution: "1260 × 2832 بكسل",
    screen_ppi: "460 بكسل لكل بوصة",
    screen_refresh_rate: "1-120Hz",
    screen_brightness: "2500 نيت (ذروة)",
    screen_protection: "Kunlun Glass 2",
    processor_name: "HiSilicon Kirin 9100 (5nm)",
    processor_cores: "ثماني النواة",
    processor_gpu: "Maleoon 920",
    processor_fabrication: "5 نانومتر",
    antutu_score: "2,100,000",
    memory_storage: "256/512GB/1TB",
    memory_ram: "12/16GB",
    memory_type: "UFS 3.1",
    memory_sd_card: "NM Card حتى 256GB",
    camera_main: "50 ميجابكسل، f/1.4-f/4.0، OIS، Variable Aperture، عدسات Leica",
    camera_ultrawide: "40 ميجابكسل، f/2.2، زاوية واسعة",
    camera_telephoto: "48 ميجابكسل، f/3.0، تقريب بصري 3.5×، OIS + 48 ميجابكسل، تقريب بصري 5.5×",
    camera_front: "13 ميجابكسل + 3D ToF",
    camera_video: "4K@60fps، HDR",
    audio_speakers: "ستيريو",
    audio_jack: "لا",
    connectivity_sim: "Dual Nano-SIM",
    connectivity_network: "5G (تردد محدود)، 4G LTE",
    connectivity_wifi: "Wi-Fi 6E",
    connectivity_bluetooth: "5.2",
    connectivity_nfc: "نعم",
    connectivity_gps: "GPS، GLONASS، Galileo، BeiDou، QZSS",
    protection_water: "IP68",
    protection_standard: "IP68",
    battery_capacity: "5500 مللي أمبير",
    battery_charging: "100 واط SuperCharge",
    battery_wireless: "80 واط لاسلكي",
    battery_reverse: "20 واط",
    software_os: "HarmonyOS 5",
    software_ui: "EMUI 15",
    sensor_fingerprint: "بصري تحت الشاشة",
    sensor_face_unlock: "3D Face Recognition",
    sensor_gyroscope: "نعم",
    sensor_compass: "نعم",
    sensor_proximity: "نعم",
    sensor_light: "نعم",
    sensor_other: "مقياس التسارع، البارومتر، مقياس الحرارة، مستشعر الأشعة تحت الحمراء"
  }
];

async function seedPhones() {
  console.log("Starting to seed 2025-2026 phones...");
  let successCount = 0;
  let errorCount = 0;

  for (const phoneData of phones2025_2026) {
    try {
      const { data: brandData, error: brandError } = await supabase
        .from("brands")
        .select("id")
        .eq("name", phoneData.brand)
        .single();

      if (brandError || !brandData) {
        console.error(`Brand ${phoneData.brand} not found. Skipping ${phoneData.name}`);
        errorCount++;
        continue;
      }

      const { data: existingPhone } = await supabase
        .from("phones")
        .select("id")
        .eq("slug", phoneData.slug)
        .maybeSingle();

      const { brand: _brand, ...phoneFields } = phoneData;
      const phonePayload = {
        ...phoneFields,
        brand_id: brandData.id,
      };

      if (existingPhone) {
        const { error } = await supabase
          .from("phones")
          .update({ ...phonePayload, updated_at: new Date().toISOString() })
          .eq("id", existingPhone.id);

        if (error) throw error;
        console.log(`✓ Updated: ${phoneData.name}`);
      } else {
        const { error } = await supabase
          .from("phones")
          .insert([phonePayload]);

        if (error) throw error;
        console.log(`✓ Inserted: ${phoneData.name}`);
      }
      successCount++;
    } catch (error) {
      console.error(`✗ Error processing ${phoneData.name}:`, error);
      errorCount++;
    }
  }

  console.log(`\nSeeding completed!`);
  console.log(`Success: ${successCount}, Errors: ${errorCount}`);
  process.exit(0);
}

seedPhones();
